#define TheDatabaseUpdateFramework1 67
#define WhatsNew 135
#define WhatsNewinVersion20200 163
#define WhatsNewinVersion21300 138
#define WhatsNewinVersion20000 156
#define NewFeatures 158
#define BugsFixedinVersion 157
#define WhatsNewinVersion10020 151
#define BugsFixedinVersion2 152
#define WhatsNewinVersion10019 148
#define SuggestionsImplementedinVersion 150
#define BugsFixedinVersion3 149
#define WhatsNewinVersion10018 146
#define BugsFixedinVersion4 147
#define WhatsNewinVersion10017 143
#define SuggestionsImplementedinVersion1 145
#define BugsFixedinVersion5 144
#define WhatsNewinVersion10016 141
#define BugsFixedinVersion6 142
#define WhatsNewinVersion10015 139
#define BugsFixedinVersion7 140
#define Overview 0
#define FirstTimeSetup 12
#define WorkspaceSetup 75
#define HowToUseItImportant 79
#define Undoaconversion 127
#define Classes 77
#define cDbUpdateHandler 2
#define PropertiesforcDbUpdateHandler 3
#define EventsforcDbUpdateHandler 7
#define MethodsforcDbUpdateHandler 8
#define cDbUpdateVersion 1
#define PropertiesforcDbUpdateVersion 4
#define EventsforcDbUpdateVersion 5
#define MethodsforcDbUpdateVersion 6
#define cDbUpdateFunctionLibrary 9
#define SQLBasedMethods 13
#define SQLMakeDatabaseChanges 100
#define SqlDataBaseCreate 19
#define SqlTableCreate 73
#define SQLTableConvertToEmbedded 123
#define SqlTableRemove 51
#define SqlTableRename 128
#define SqlViewRemove 52
#define SqlColumnAdd 54
#define SqlColumnChange 55
#define SqlColumnRemove 56
#define SqlColumnRename 28
#define SqlColumnDefaultValue 121
#define SqlColumnNullable 122
#define SqlColumnUpdateValue 133
#define SQLUtilityFunctions 102
#define SQLUtilColumnExists 104
#define SqlUtilEnumerateServers 24
#define SqlUtilEnumerateDatabases 25
#define SqlUtilEnumerateTableSpaces 83
#define SqlUtilEnumerateSchemas 84
#define SqlUtilEnumerateTables 26
#define SqlUtilEnumerateColumns 27
#define SqlUtilEnumerateIntFiles 46
#define SqlUtilEnumerateLoggedInUsers 49
#define SqlUtilChangeIntFilesToConnectio 53
#define SqlUtilRefreshIntFile 85
#define SqlUtilExecuteQuery 86
#define SqlUtilExecuteResource 14
#define SqlUtilCreateFileFromMemory 48
#define SqlUtilBackupDatabaseToDisk 103
#define SqlUtilTableIsAttached 115
#define SQLUtilDefaultNullValue 119
#define SQLUtilTableIsViewType 120
#define SqlUtilGUIDTempTableName 129
#define APIBasedMethods 16
#define APIMakeDatabaseChanges 42
#define ApiTableAttachtToSQL 66
#define ApiTableAttachALLToSQL 154
#define ApiTableChangeAttribute 105
#define ApiTableConvertToSQL 87
#define ApiTableMoveFileListEntry 164
#define ApiTableChangeFileListSlot 155
#define ApiTableConvertToSQL_Ex 74
#define ApiTableConvertAllAddException 124
#define ApiTableConvertALLToSQL 125
#define ApiTableCopyData 126
#define ApiTableCreate 88
#define ApiTableCreateAlias 29
#define ApiTableRelate 30
#define ApiTableRemove 32
#define ApiTableRemoveRelation 31
#define ApiTableRename 33
#define ApiTableRenameAlias 34
#define ApiTableUpdate 159
#define ApiColumnAdd 22
#define ApiColumnChange 35
#define ApiColumnChangeMainIndex 36
#define ApiColumnMove 38
#define ApiColumnRemove 37
#define ApiColumnRename 39
#define ApiColumnUpdateValue 132
#define ApiIndexCreate 47
#define ApiIndexCreateByFieldNames 134
#define ApiIndexChangeDirection 99
#define ApiIndexChangeUppercase 41
#define ApiIndexRemove 101
#define ApiIndexCreateEx 136
#define APIUtilityFunctions 106
#define UtilCodeMasterAddValue 40
#define UtilCodeMasterChangeValue 43
#define UtilCodeMasterRemoveValue 44
#define UtilityMethods 45
#define UtilLowestAllowedMSSQLDRV_And_Cl 160
#define UtilPrepareDataFolderForSQLConve 161
#define UtilEnumerateOverlapFields 112
#define UtilEnumerateColumnTypes 97
#define UtilColumnTypeToInteger 111
#define UtilColumnTypeToString 98
#define UtilTableHandleToString 63
#define UtilTableNameToHandle 64
#define UtilColumnExists 65
#define UtilTableIsAlias 113
#define UtilTableOpen 114
#define UtilTableNumberIsInUse 116
#define UtilTableIsSQL 117
#define UtilTableIsSQLByRootName 118
#define HowtoAddSQLKeywords 130
#define cDbUpdateLogFile 57
#define PropertiesforcDbUpdateLogFile 58
#define MethodsforcDbUpdateLogFile 60
#define cDbUpdateUserCount 59
#define PropertiesforcDbUpdateUserCount 61
#define MethodsforcDbUpdateUserCount 62
#define cSQLConnectionHandler 10
#define PropertiesforcSQLConnectionHandl 23
#define MethodsforcSQLConnectionHandler 68
#define cSQLConnectionIniFile 21
#define PropertiesforcSQLConnectionIniFi 69
#define MethodsforcSQLConnectionIniFile 70
#define cDbUpdateDatabaseDriver 76
#define MethodsforcDbUpdateDatabaseDrive 81
#define PropertiesforcDbUpdateDatabaseDr 80
#define FrameworkStructs 15
#define tSQLConnection 20
#define tSQLScriptArray 17
#define tSQLErrorArray 18
#define tDbUpdateError 82
#define tColumnType 89
#define tSQLLoggedInUser 50
#define tAPITableNameInfo 162
#define tAPIColumn 153
#define MappingofSQLDataTypes 90
#define DataFlexReplacementDataTypes 110
#define IBMDB2andDB2_DRV 93
#define MicrosoftSQLServerandMSSQLDRV 91
#define MicrosoftSQLServerandSQLFLEX 92
#define MySQLDatabaseandMDSMySQL 94
#define OracleDatabaseandORAFLEX 96
#define PostgreSQLDatabaseandMDSPgSQL 95
#define Commands 11
#define Tools 78
#define DUFSQLConnectionsTool 71
#define DUFCodeGenerator 137
#define Howtheautomaticupdateworks 165
#define DbUpdateFrameworkTestProgram 131
#define CreateDbVersionTableTool 72
#define License 107
#define Disclaimer 108
#define Feedback 109
