#REM Generated - DUF icon
#REM =============
Copy database-server-filled-update.ico  ..\DbUpdateFrameworkDF19.ico
Copy button-info.ico  ..\ActionAbout1.ico
Copy button-add.ico  ..\ActionAdd1.ico
Copy toggle-on.ico  ..\ToggleOn1.ico
Copy toggle-off.ico  ..\ToggleOff1.ico
Copy clipboard-copy.ico  ..\ActionCopy1.ico
Copy clipboard-cut.ico  ..\ActionCut1.ico
Copy exit.ico  ..\ActionExit1.ico
Copy button-circle-find.ico  ..\ActionPrompt1.ico
Copy review-compare-database.ico  ..\DbCompare1.ico
Copy button-help.ico  ..\ActionHelp1.ico
Copy button-help-internet.ico  ..\ActionHelpInternet1.ico
Copy clipboard-paste.ico  ..\ActionPaste1.ico
Copy save-filled.ico  ..\ActionSave1.ico
Copy save-as-filled.ico  ..\ActionSaveAs1.ico
Copy settings-options-edit.ico  ..\EditorSettings1.ico
Copy report.ico  ..\ViewReport1.ico
Copy select-all.ico  ..\SelectAll1.ico
Copy select-inverse.ico  ..\SelectInvert1.ico
Copy select-none.ico  ..\SelectNone1.ico
Copy settings-options.ico  ..\Settings1.ico
Copy toggle-off.ico  ..\ToggleOff1.ico
Copy toggle-on.ico  ..\ToggleOn1.ico
Copy save-filled.ico  ..\ActionSaveRecord1.ico
Copy sql-gear.ico  ..\SQLSettings1.ico
Copy tables-ok.ico  ..\SelectTables1.ico
Copy script-filled-database.ico  ..\SqlScript1.ico
Copy page-new.ico  ..\ActionClear1.ico
Copy folder-open-filled.ico  ..\ActionOpen1.ico
Copy eye.ico  ..\ViewPassword1.ico
Copy database-filled-padlock.ico  ..\ActionLogin1.ico
Copy script-save.ico  ..\ActionSaveCode1.ico
Copy report-save.ico  ..\ActionPrintSave1.ico
Copy folder-open-filled-browse.ico  ..\ActionOpenFolder1.ico
Copy script-browse.ico  ..\ViewSourceCode1.ico
Copy folder-filled-arrow-left.ico  ..\FolderLeft1.ico
Copy folder-filled-arrow-right.ico  ..\FolderRight1.ico
rem Copy computer-server-database.ico  ..\SQLConnections.ico
Copy database-server-filled-gear.ico  ..\SQLConnections1.ico
Copy button-circle-edit.ico  ..\ActionEdit1.ico
Copy button-refresh.ico  ..\ActionRefresh1.ico
Copy database-filled-browse.ico  ..\DatabaseLookup1.ico
Copy computer-server-browse.ico  ..\ServerLookup1.ico
Copy table-column-new.ico  ..\ActionAddColumn1.ico
Copy table-new.ico  ..\ActionAddTable1.ico
Copy database-filled-new.ico  ..\ActionCreateDatabase1.ico
Copy table-trash.ico  ..\ActionDeleteTable1.ico
Copy document-text.ico  ..\ActionDocument1.ico
Copy table-column-trash.ico  ..\DeleteColumn1.ico
Copy tab-sql-database.ico  ..\TestTools1.ico
Copy database-filled-disc.ico  ..\DbBackup1.ico
rem Copy com-addins.ico  ..\DriverSettings.ico
Copy playlist-gear.ico  ..\DriverSettings1.ico
Copy data-export.ico  ..\ActionExport1.ico
Copy database-filled-script-filled.ico ..\DUFUpdateCodeGenerator1.ico