//
// *** The Database Update Framework Include file ***
// Language constant declarations for all classes included in "DUF - The Database Update Framework"
// They have all been placed in this central spot to make translations to various languages more convenient.
//
//
Use LanguageText.Pkg

// *** cSQLConnectionsIniFile Class Language Constants ***
//
#IFSAME Language$Current Language$English
    Define CS_DUF_DuplicateConnectionIDPre  for "Cannot register connection ID"
    Define CS_DUF_DuplicateConnectionIDPost for "This ID already exists."
#ENDIF

#IFSAME Language$Current Language$Nederlands
    Define CS_DUF_DuplicateConnectionIDPre  for "Cannot register connection ID"
    Define CS_DUF_DuplicateConnectionIDPost for "This ID already exists."
#ENDIF

#IFSAME Language$Current Language$Svenska
    Define CS_DUF_DuplicateConnectionIDPre  for "Cannot register connection ID"
    Define CS_DUF_DuplicateConnectionIDPost for "This ID already exists."
#ENDIF

#IFSAME Language$Current Language$Deutsch
    Define CS_DUF_DuplicateConnectionIDPre  for "Cannot register connection ID"
    Define CS_DUF_DuplicateConnectionIDPost for "This ID already exists."
#ENDIF

#IFSAME Language$Current Language$Dansk
    Define CS_DUF_DuplicateConnectionIDPre  for "Cannot register connection ID"
    Define CS_DUF_DuplicateConnectionIDPost for "This ID already exists."
#ENDIF

#IFSAME Language$Current Language$Portugues
    Define CS_DUF_DuplicateConnectionIDPre  for "Cannot register connection ID"
    Define CS_DUF_DuplicateConnectionIDPost for "This ID already exists."
#ENDIF

#IFSAME Language$Current Language$Francais
    Define CS_DUF_DuplicateConnectionIDPre  for "Cannot register connection ID"
    Define CS_DUF_DuplicateConnectionIDPost for "This ID already exists."
#ENDIF

#IFSAME Language$Current Language$Italiano
    Define CS_DUF_DuplicateConnectionIDPre  for "Cannot register connection ID"
    Define CS_DUF_DuplicateConnectionIDPost for "This ID already exists."
#ENDIF

#IFSAME Language$Current Language$Espanol
    Define CS_DUF_DuplicateConnectionIDPre  for "Cannot register connection ID"
    Define CS_DUF_DuplicateConnectionIDPost for "This ID already exists."
#ENDIF

#IFSAME Language$Current Language$Norsk
    Define CS_DUF_DuplicateConnectionIDPre  for "Cannot register connection ID"
    Define CS_DUF_DuplicateConnectionIDPost for "This ID already exists."
#ENDIF

#IFSame Language$Current = Language$Russian
    Define CS_DUF_DuplicateConnectionIDPre  for "Cannot register connection ID"
    Define CS_DUF_DuplicateConnectionIDPost for "This ID already exists."
#ENDIF

#IFSame Language$Current = Language$Polish
    Define CS_DUF_DuplicateConnectionIDPre  for "Cannot register connection ID"
    Define CS_DUF_DuplicateConnectionIDPost for "This ID already exists."
#ENDIF

#IFSame Language$Current = Language$Hungarian
    Define CS_DUF_DuplicateConnectionIDPre  for "Cannot register connection ID"
    Define CS_DUF_DuplicateConnectionIDPost for "This ID already exists."
#ENDIF


// *** cSQLConnectionsHandler Class Language Constants ***
//
#IFSAME Language$Current Language$English
    Define CS_DUF_SetupErrorcConnection  for "Cannot login to the database server as the cConnection hasn't been setup properly. Can't continue. Program will now exit."
    Define CS_DUF_CannotLoginToServer    for "Could not login to the database server. Can't continue. Program will now exit."
    Define CS_DUF_ErrorText              for "\n\nError Text:"
#ENDIF

#IFSAME Language$Current Language$Nederlands
    Define CS_DUF_CannotLogincConnection for "Cannot login to the database server as the cConnection hasn't been setup properly. Can't continue. Program will now exit."
    Define CS_DUF_CannotLoginToServer    for "Could not login to the database server. Can't continue. Program will now exit."
    Define CS_DUF_ErrorText              for "\n\nError Text:"
#ENDIF

#IFSAME Language$Current Language$Svenska
    Define CS_DUF_CannotLogincConnection for "Cannot login to the database server as the cConnection hasn't been setup properly. Can't continue. Program will now exit."
    Define CS_DUF_CannotLoginToServer    for "Could not login to the database server. Can't continue. Program will now exit."
    Define CS_DUF_ErrorText              for "\n\nError Text:"
#ENDIF

#IFSAME Language$Current Language$Deutsch
    Define CS_DUF_CannotLogincConnection for "Cannot login to the database server as the cConnection hasn't been setup properly. Can't continue. Program will now exit."
    Define CS_DUF_CannotLoginToServer    for "Could not login to the database server. Can't continue. Program will now exit."
    Define CS_DUF_ErrorText              for "\n\nError Text:"
#ENDIF

#IFSAME Language$Current Language$Dansk
    Define CS_DUF_CannotLogincConnection for "Cannot login to the database server as the cConnection hasn't been setup properly. Can't continue. Program will now exit."
    Define CS_DUF_CannotLoginToServer    for "Could not login to the database server. Can't continue. Program will now exit."
    Define CS_DUF_ErrorText              for "\n\nError Text:"
#ENDIF

#IFSAME Language$Current Language$Portugues
    Define CS_DUF_CannotLogincConnection for "Cannot login to the database server as the cConnection hasn't been setup properly. Can't continue. Program will now exit."
    Define CS_DUF_CannotLoginToServer    for "Could not login to the database server. Can't continue. Program will now exit."
    Define CS_DUF_ErrorText              for "\n\nError Text:"
#ENDIF

#IFSAME Language$Current Language$Francais
    Define CS_DUF_CannotLogincConnection for "Cannot login to the database server as the cConnection hasn't been setup properly. Can't continue. Program will now exit."
    Define CS_DUF_CannotLoginToServer    for "Could not login to the database server. Can't continue. Program will now exit."
    Define CS_DUF_ErrorText              for "\n\nError Text:"
#ENDIF

#IFSAME Language$Current Language$Italiano
    Define CS_DUF_CannotLogincConnection for "Cannot login to the database server as the cConnection hasn't been setup properly. Can't continue. Program will now exit."
    Define CS_DUF_CannotLoginToServer    for "Could not login to the database server. Can't continue. Program will now exit."
    Define CS_DUF_ErrorText              for "\n\nError Text:"
#ENDIF

#IFSAME Language$Current Language$Espanol
    Define CS_DUF_CannotLogincConnection for "Cannot login to the database server as the cConnection hasn't been setup properly. Can't continue. Program will now exit."
    Define CS_DUF_CannotLoginToServer    for "Could not login to the database server. Can't continue. Program will now exit."
    Define CS_DUF_ErrorText              for "\n\nError Text:"
#ENDIF

#IFSAME Language$Current Language$Norsk
    Define CS_DUF_CannotLogincConnection for "Cannot login to the database server as the cConnection hasn't been setup properly. Can't continue. Program will now exit."
    Define CS_DUF_CannotLoginToServer    for "Could not login to the database server. Can't continue. Program will now exit."
    Define CS_DUF_ErrorText              for "\n\nError Text:"
#ENDIF

#IFSame Language$Current = Language$Russian
    Define CS_DUF_CannotLogincConnection for "Cannot login to the database server as the cConnection hasn't been setup properly. Can't continue. Program will now exit."
    Define CS_DUF_CannotLoginToServer    for "Could not login to the database server. Can't continue. Program will now exit."
    Define CS_DUF_ErrorText              for "\n\nError Text:"
#ENDIF

#IFSame Language$Current = Language$Polish
    Define CS_DUF_CannotLogincConnection for "Cannot login to the database server as the cConnection hasn't been setup properly. Can't continue. Program will now exit."
    Define CS_DUF_CannotLoginToServer    for "Could not login to the database server. Can't continue. Program will now exit."
    Define CS_DUF_ErrorText              for "\n\nError Text:"
#ENDIF

#IFSame Language$Current = Language$Hungarian
    Define CS_DUF_CannotLogincConnection for "Cannot login to the database server as the cConnection hasn't been setup properly. Can't continue. Program will now exit."
    Define CS_DUF_CannotLoginToServer    for "Could not login to the database server. Can't continue. Program will now exit."
    Define CS_DUF_ErrorText              for "\n\nError Text:"
#ENDIF

// *** cDbUpdateFunctionLibrary Class Language Constants ***
// 
#IFSAME Language$Current Language$English
    Define CS_SQLConnectError       for "SQL error. Could not connect to the SQL database manager"
    Define CS_SQLAttachError        for "Could not attach to the database:"
    Define CS_SQLDeletingIndex      for "Deleting index"
    Define CS_SQLCopyingData        for "Copying data"
    Define CS_SQLCreatingIndex      for "Creating index"
#ENDIF

#IFSAME Language$Current Language$Nederlands
    Define CS_SQLConnectError       for "SQL error. Could not connect to the SQL database manager"
    Define CS_SQLAttachError        for "Could not attach to the database:"
    Define CS_SQLDeletingIndex      for "Deleting index"
    Define CS_SQLCopyingData        for "Copying data"
    Define CS_SQLCreatingIndex      for "Creating index"
#ENDIF

#IFSAME Language$Current Language$Svenska
    Define CS_SQLConnectError       for "SQL Fel. Kunde ej f† kontakt med SQL Database Manager"
    Define CS_SQLAttachError        for "Fick ej kontakt med databasen:"
    Define CS_SQLDeletingIndex      for "Tar bort index"
    Define CS_SQLCopyingData        for "Kopierar data"
    Define CS_SQLCreatingIndex      for "Skapar index"
#ENDIF

#IFSAME Language$Current Language$Deutsch
    Define CS_SQLConnectError       for "SQL error. Could not connect to the SQL database manager"
    Define CS_SQLAttachError        for "Could not attach to the database:"
    Define CS_SQLDeletingIndex      for "Deleting index"
    Define CS_SQLCopyingData        for "Copying data"
    Define CS_SQLCreatingIndex      for "Creating index"
#ENDIF

#IFSAME Language$Current Language$Dansk
    Define CS_SQLConnectError       for "SQL error. Could not connect to the SQL database manager"
    Define CS_SQLAttachError        for "Could not attach to the database:"
    Define CS_SQLDeletingIndex      for "Deleting index"
    Define CS_SQLCopyingData        for "Copying data"
    Define CS_SQLCreatingIndex      for "Creating index"
#ENDIF

#IFSAME Language$Current Language$Portugues
    Define CS_SQLConnectError       for "SQL error. Could not connect to the SQL database manager"
    Define CS_SQLAttachError        for "Could not attach to the database:"
    Define CS_SQLDeletingIndex      for "Deleting index"
    Define CS_SQLCopyingData        for "Copying data"
    Define CS_SQLCreatingIndex      for "Creating index"
#ENDIF

#IFSAME Language$Current Language$Francais
    Define CS_SQLConnectError       for "SQL error. Could not connect to the SQL database manager"
    Define CS_SQLAttachError        for "Could not attach to the database:"
    Define CS_SQLDeletingIndex      for "Deleting index"
    Define CS_SQLCopyingData        for "Copying data"
    Define CS_SQLCreatingIndex      for "Creating index"
#ENDIF

#IFSAME Language$Current Language$Italiano
    Define CS_SQLConnectError       for "SQL error. Could not connect to the SQL database manager"
    Define CS_SQLAttachError        for "Could not attach to the database:"
    Define CS_SQLDeletingIndex      for "Deleting index"
    Define CS_SQLCopyingData        for "Copying data"
    Define CS_SQLCreatingIndex      for "Creating index"
#ENDIF

#IFSAME Language$Current Language$Espanol
    Define CS_SQLConnectError       for "SQL error. Could not connect to the SQL database manager"
    Define CS_SQLAttachError        for "Could not attach to the database:"
    Define CS_SQLDeletingIndex      for "Deleting index"
    Define CS_SQLCopyingData        for "Copying data"
    Define CS_SQLCreatingIndex      for "Creating index"
#ENDIF

#IFSAME Language$Current Language$Norsk
    Define CS_SQLConnectError       for "SQL error. Could not connect to the SQL database manager"
    Define CS_SQLAttachError        for "Could not attach to the database:"
    Define CS_SQLDeletingIndex      for "Deleting index"
    Define CS_SQLCopyingData        for "Copying data"
    Define CS_SQLCreatingIndex      for "Creating index"
#ENDIF

#IFSame Language$Current = Language$Russian
    Define CS_SQLConnectError       for "SQL error. Could not connect to the SQL database manager"
    Define CS_SQLAttachError        for "Could not attach to the database:"
    Define CS_SQLDeletingIndex      for "Deleting index"
    Define CS_SQLCopyingData        for "Copying data"
    Define CS_SQLCreatingIndex      for "Creating index"
#ENDIF

#IFSame Language$Current = Language$Polish
    Define CS_SQLConnectError       for "SQL error. Could not connect to the SQL database manager"
    Define CS_SQLAttachError        for "Could not attach to the database:"
    Define CS_SQLDeletingIndex      for "Deleting index"
    Define CS_SQLCopyingData        for "Copying data"
    Define CS_SQLCreatingIndex      for "Creating index"
#ENDIF

#IFSame Language$Current = Language$Hungarian
    Define CS_SQLConnectError       for "SQL error. Could not connect to the SQL database manager"
    Define CS_SQLAttachError        for "Could not attach to the database:"
    Define CS_SQLDeletingIndex      for "Deleting index"
    Define CS_SQLCopyingData        for "Copying data"
    Define CS_SQLCreatingIndex      for "Creating index"
#ENDIF

// *** cDbUpdateVersion Class Language Constants ***
//
#IFSAME Language$Current Language$English
    Define CS_UpdateVersion     for "Updating database"
    Define CS_UpdateFromVersion for "from version"
    Define CS_UpdateToVersion   for "to version:"
    Define CS_DbUpdateTableMissing for "Cannot open the 'DbVersion' table that is used when updating the database! Cannot continue!"
#ENDIF

#IFSAME Language$Current Language$Nederlands
    Define CS_UpdateVersion     for "Updating database"
    Define CS_UpdateFromVersion for "from version" 
    Define CS_UpdateToVersion   for "to version:"
    Define CS_DbUpdateTableMissing for "Cannot open the 'DbVersion' table that is used when updating the database! Cannot continue!"
#ENDIF

#IFSAME Language$Current Language$Svenska
    Define CS_UpdateVersion     for "Uppdaterar databas"
    Define CS_UpdateFromVersion for "fr†n version" 
    Define CS_UpdateToVersion   for "till version:"
    Define CS_DbUpdateTableMissing for "Kan inte ”ppna 'DbVersion' tabellen som anv„nds d† databasen ska uppdateras! Kan inte forts„tta!"
#ENDIF

#IFSAME Language$Current Language$Deutsch
    Define CS_UpdateVersion     for "Updating database"
    Define CS_UpdateFromVersion for "from version" 
    Define CS_UpdateToVersion   for "to version:"
    Define CS_DbUpdateTableMissing for "Cannot open the 'DbVersion' table that is used when updating the database! Cannot continue!"
#ENDIF

#IFSAME Language$Current Language$Dansk
    Define CS_UpdateVersion     for "Updating database"
    Define CS_UpdateFromVersion for "from version" 
    Define CS_UpdateToVersion   for "to version:"
    Define CS_DbUpdateTableMissing for "Cannot open the 'DbVersion' table that is used when updating the database! Cannot continue!"
#ENDIF

#IFSAME Language$Current Language$Portugues
    Define CS_UpdateVersion     for "Updating database"
    Define CS_UpdateFromVersion for "from version" 
    Define CS_UpdateToVersion   for "to version:"
    Define CS_DbUpdateTableMissing for "Cannot open the 'DbVersion' table that is used when updating the database! Cannot continue!"
#ENDIF

#IFSAME Language$Current Language$Francais
    Define CS_UpdateVersion     for "Updating database"
    Define CS_UpdateFromVersion for "from version" 
    Define CS_UpdateToVersion   for "to version:"
    Define CS_DbUpdateTableMissing for "Cannot open the 'DbVersion' table that is used when updating the database! Cannot continue!"
#ENDIF

#IFSAME Language$Current Language$Italiano
    Define CS_UpdateVersion     for "Updating database"
    Define CS_UpdateFromVersion for "from version" 
    Define CS_UpdateToVersion   for "to version:"
    Define CS_DbUpdateTableMissing for "Cannot open the 'DbVersion' table that is used when updating the database! Cannot continue!"
#ENDIF

#IFSAME Language$Current Language$Espanol
    Define CS_UpdateVersion     for "Updating database"
    Define CS_UpdateFromVersion for "from version" 
    Define CS_UpdateToVersion   for "to version:"
    Define CS_DbUpdateTableMissing for "Cannot open the 'DbVersion' table that is used when updating the database! Cannot continue!"
#ENDIF

#IFSAME Language$Current Language$Norsk
    Define CS_UpdateVersion     for "Updating database"
    Define CS_UpdateFromVersion for "from version" 
    Define CS_UpdateToVersion   for "to version:"
    Define CS_DbUpdateTableMissing for "Cannot open the 'DbVersion' table that is used when updating the database! Cannot continue!"
#ENDIF

#IFSame Language$Current = Language$Russian
    Define CS_UpdateVersion     for "Updating database"
    Define CS_UpdateFromVersion for "from version" 
    Define CS_UpdateToVersion   for "to version:"
    Define CS_DbUpdateTableMissing for "Cannot open the 'DbVersion' table that is used when updating the database! Cannot continue!"
#ENDIF

#IFSame Language$Current = Language$Polish
    Define CS_UpdateVersion     for "Updating database"
    Define CS_UpdateFromVersion for "from version" 
    Define CS_UpdateToVersion   for "to version:"
    Define CS_DbUpdateTableMissing for "Cannot open the 'DbVersion' table that is used when updating the database! Cannot continue!"
#ENDIF

#IFSame Language$Current = Language$Hungarian
    Define CS_UpdateVersion     for "Updating database"
    Define CS_UpdateFromVersion for "from version" 
    Define CS_UpdateToVersion   for "to version:"
    Define CS_DbUpdateTableMissing for "Cannot open the 'DbVersion' table that is used when updating the database! Cannot continue!"
#ENDIF

// *** cDbUpdateHandler.inc Class Language Constants ***
// 
#IFSAME Language$Current Language$English
    Define CS_DatabaseNeedsUpdate for ("The database needs to be updated." + "\n\nNB! The database may not be in use while this work is performed. Make sure that nobody else is using the application before clicking 'Yes' below.\n\n" + "Start update now?")
    Define CS_HeaderUpdateText    for "Important!"
    Define CS_DatabaseInUseText   for "There are others using the application/database or at least one table could NOT be opened exclusively. Please close all other applications using the database and try again. The Application will now close."
    Define CS_WorkingHeaderText   for "Working!"
    Define CS_WorkingUpdateText   for "The database is being updated. Please wait..."
    Define CS_DatabaseUpdatedText for "Ready! The database was updated."
    Define CS_DatabaseCheckedText for "Ready! The database was checked but no updates was needed."
    Define CS_DbUpdatedErrorText  for "One or more errors occured while the database was updated. Please check the logfile.\n\nThe program will now close."
    Define CS_UpdateInProgressTxt for ("System locked!\n\nThe database is being updated. Please try again later...\n\n" * "The program will now close.")
#ENDIF

#IFSAME Language$Current Language$Nederlands
    Define CS_DatabaseNeedsUpdate for ("The database needs to be updated." + "\n\nNB! The database may not be in use while this work is performed. Make sure that nobody else is using the application before clicking 'Yes' below.\n\n" + "Start update now?")
    Define CS_HeaderUpdateText    for "Important!"
    Define CS_DatabaseInUseText   for "There are others using the application/database or at least one table could NOT be opened exclusively. Please close all other applications using the database and try again. The Application will now close."
    Define CS_WorkingHeaderText   for "Working!"
    Define CS_WorkingUpdateText   for "The database is being updated. Please wait..."
    Define CS_DatabaseUpdatedText for "Ready! The database was updated."
    Define CS_DatabaseCheckedText for "Ready! The database was checked but no updates was needed."
    Define CS_DbUpdatedErrorText  for "One or more errors occured while the database was updated. Please check the logfile.\n\nThe program will now close."
    Define CS_UpdateInProgressTxt for ("System locked!\n\nThe database is being updated. Please try again later...\n\n" * "The program will now close.")
#ENDIF

#IFSAME Language$Current Language$Svenska
    Define CS_DatabaseNeedsUpdate for ("Databasen beh”ver uppdateras." + "\n\nOBS! Databasen f†r ej anv„ndas medan detta arbete sker. Var god och s„kerst„ll att ingen annan k”r programmet eller p† annat s„tt anv„nder databasen som anv„nds f”r programmet innan du klicka p† 'Ja' nedan.\n\n" + "Starta uppdateringen nu?")
    Define CS_HeaderUpdateText    for "Viktigt!"
    Define CS_DatabaseInUseText   for "Det verkar finnas andra personer som k”r programmet eller anv„nder databasen, eftersom †tminstone en tabell ej kunde ”ppnas exklisivt. Var v„nlig st„ng alla andra applikationer som kan anv„nda databasen och f”rs”k igen. Programmet kommer nu att avslutas."
    Define CS_WorkingHeaderText   for "Arbetar!"
    Define CS_WorkingUpdateText   for "Databasen h†ller p† att uppdateras. Var god v„nta..."
    Define CS_DatabaseUpdatedText for "Klart! Databasen „r nu uppdaterad."
    Define CS_DatabaseCheckedText for "Ready! The database was checked but no updates was needed."
    Define CS_DbUpdatedErrorText  for "Ett eller flera fel uppstod tyv„rr under uppdateringen av databasen. Var god kontrollera fel-loggen.\n\nProgrammet kommer nu att avslutas."
    Define CS_UpdateInProgressTxt for ("Systemet „r l†st!\n\nDatabasen h†ller p† att uppdateras. Var god v„nta och f”rs”k †ter senare...\n\n" * "Programmet kommer nu att avslutas.")
#ENDIF

#IFSAME Language$Current Language$Deutsch
    Define CS_DatabaseNeedsUpdate for ("The database needs to be updated." + "\n\nNB! The database may not be in use while this work is performed. Make sure that nobody else is using the application before clicking 'Yes' below.\n\n" + "Start update now?")
    Define CS_HeaderUpdateText    for "Important!"
    Define CS_DatabaseInUseText   for "There are others using the application/database or at least one table could NOT be opened exclusively. Please close all other applications using the database and try again. The Application will now close."
    Define CS_WorkingHeaderText   for "Working!"
    Define CS_WorkingUpdateText   for "The database is being updated. Please wait..."
    Define CS_DatabaseUpdatedText for "Ready! The database was updated."
    Define CS_DatabaseCheckedText for "Ready! The database was checked but no updates was needed."
    Define CS_DbUpdatedErrorText  for "One or more errors occured while the database was updated. Please check the logfile.\n\nThe program will now close."
    Define CS_UpdateInProgressTxt for ("System locked!\n\nThe database is being updated. Please try again later...\n\n" * "The program will now close.")
#ENDIF

#IFSAME Language$Current Language$Dansk
    Define CS_DatabaseNeedsUpdate for ("The database needs to be updated." + "\n\nNB! The database may not be in use while this work is performed. Make sure that nobody else is using the application before clicking 'Yes' below.\n\n" + "Start update now?")
    Define CS_HeaderUpdateText    for "Important!"
    Define CS_DatabaseInUseText   for "There are others using the application/database or at least one table could NOT be opened exclusively. Please close all other applications using the database and try again. The Application will now close."
    Define CS_WorkingHeaderText   for "Working!"
    Define CS_WorkingUpdateText   for "The database is being updated. Please wait..."
    Define CS_DatabaseUpdatedText for "Ready! The database was updated."
    Define CS_DatabaseCheckedText for "Ready! The database was checked but no updates was needed."
    Define CS_DbUpdatedErrorText  for "One or more errors occured while the database was updated. Please check the logfile.\n\nThe program will now close."
    Define CS_UpdateInProgressTxt for ("System locked!\n\nThe database is being updated. Please try again later...\n\n" * "The program will now close.")
#ENDIF

#IFSAME Language$Current Language$Portugues
    Define CS_DatabaseNeedsUpdate for ("The database needs to be updated." + "\n\nNB! The database may not be in use while this work is performed. Make sure that nobody else is using the application before clicking 'Yes' below.\n\n" + "Start update now?")
    Define CS_HeaderUpdateText    for "Important!"
    Define CS_DatabaseInUseText   for "There are others using the application/database or at least one table could NOT be opened exclusively. Please close all other applications using the database and try again. The Application will now close."
    Define CS_WorkingHeaderText   for "Working!"
    Define CS_WorkingUpdateText   for "The database is being updated. Please wait..."
    Define CS_DatabaseUpdatedText for "Ready! The database was updated."
    Define CS_DatabaseCheckedText for "Ready! The database was checked but no updates was needed."
    Define CS_DbUpdatedErrorText  for "One or more errors occured while the database was updated. Please check the logfile.\n\nThe program will now close."
    Define CS_UpdateInProgressTxt for ("System locked!\n\nThe database is being updated. Please try again later...\n\n" * "The program will now close.")
#ENDIF

#IFSAME Language$Current Language$Francais
    Define CS_DatabaseNeedsUpdate for ("The database needs to be updated." + "\n\nNB! The database may not be in use while this work is performed. Make sure that nobody else is using the application before clicking 'Yes' below.\n\n" + "Start update now?")
    Define CS_HeaderUpdateText    for "Important!"
    Define CS_DatabaseInUseText   for "There are others using the application/database or at least one table could NOT be opened exclusively. Please close all other applications using the database and try again. The Application will now close."
    Define CS_WorkingHeaderText   for "Working!"
    Define CS_WorkingUpdateText   for "The database is being updated. Please wait..."
    Define CS_DatabaseUpdatedText for "Ready! The database was updated."
    Define CS_DatabaseCheckedText for "Ready! The database was checked but no updates was needed."
    Define CS_DbUpdatedErrorText  for "One or more errors occured while the database was updated. Please check the logfile.\n\nThe program will now close."
    Define CS_UpdateInProgressTxt for ("System locked!\n\nThe database is being updated. Please try again later...\n\n" * "The program will now close.")
#ENDIF

#IFSAME Language$Current Language$Italiano
    Define CS_DatabaseNeedsUpdate for ("The database needs to be updated." + "\n\nNB! The database may not be in use while this work is performed. Make sure that nobody else is using the application before clicking 'Yes' below.\n\n" + "Start update now?")
    Define CS_HeaderUpdateText    for "Important!"
    Define CS_DatabaseInUseText   for "There are others using the application/database or at least one table could NOT be opened exclusively. Please close all other applications using the database and try again. The Application will now close."
    Define CS_WorkingHeaderText   for "Working!"
    Define CS_WorkingUpdateText   for "The database is being updated. Please wait..."
    Define CS_DatabaseUpdatedText for "Ready! The database was updated."
    Define CS_DatabaseCheckedText for "Ready! The database was checked but no updates was needed."
    Define CS_DbUpdatedErrorText  for "One or more errors occured while the database was updated. Please check the logfile.\n\nThe program will now close."
    Define CS_UpdateInProgressTxt for ("System locked!\n\nThe database is being updated. Please try again later...\n\n" * "The program will now close.")
#ENDIF

#IFSAME Language$Current Language$Espanol
    Define CS_DatabaseNeedsUpdate for ("The database needs to be updated." + "\n\nNB! The database may not be in use while this work is performed. Make sure that nobody else is using the application before clicking 'Yes' below.\n\n" + "Start update now?")
    Define CS_HeaderUpdateText    for "Important!"
    Define CS_DatabaseInUseText   for "There are others using the application/database or at least one table could NOT be opened exclusively. Please close all other applications using the database and try again. The Application will now close."
    Define CS_WorkingHeaderText   for "Working!"
    Define CS_WorkingUpdateText   for "The database is being updated. Please wait..."
    Define CS_DatabaseUpdatedText for "Ready! The database was updated."
    Define CS_DatabaseCheckedText for "Ready! The database was checked but no updates was needed."
    Define CS_DbUpdatedErrorText  for "One or more errors occured while the database was updated. Please check the logfile.\n\nThe program will now close."
    Define CS_UpdateInProgressTxt for ("System locked!\n\nThe database is being updated. Please try again later...\n\n" * "The program will now close.")
#ENDIF

#IFSAME Language$Current Language$Norsk
    Define CS_DatabaseNeedsUpdate for ("The database needs to be updated." + "\n\nNB! The database may not be in use while this work is performed. Make sure that nobody else is using the application before clicking 'Yes' below.\n\n" + "Start update now?")
    Define CS_HeaderUpdateText    for "Important!"
    Define CS_DatabaseInUseText   for "There are others using the application/database or at least one table could NOT be opened exclusively. Please close all other applications using the database and try again. The Application will now close."
    Define CS_WorkingHeaderText   for "Working!"
    Define CS_WorkingUpdateText   for "The database is being updated. Please wait..."
    Define CS_DatabaseUpdatedText for "Ready! The database was updated."
    Define CS_DatabaseCheckedText for "Ready! The database was checked but no updates was needed."
    Define CS_DbUpdatedErrorText  for "One or more errors occured while the database was updated. Please check the logfile.\n\nThe program will now close."
    Define CS_UpdateInProgressTxt for ("System locked!\n\nThe database is being updated. Please try again later...\n\n" * "The program will now close.")
#ENDIF

#IFSame Language$Current = Language$Russian
    Define CS_DatabaseNeedsUpdate for ("The database needs to be updated." + "\n\nNB! The database may not be in use while this work is performed. Make sure that nobody else is using the application before clicking 'Yes' below.\n\n" + "Start update now?")
    Define CS_HeaderUpdateText    for "Important!"
    Define CS_DatabaseInUseText   for "There are others using the application/database or at least one table could NOT be opened exclusively. Please close all other applications using the database and try again. The Application will now close."
    Define CS_WorkingHeaderText   for "Working!"
    Define CS_WorkingUpdateText   for "The database is being updated. Please wait..."
    Define CS_DatabaseUpdatedText for "Ready! The database was updated."
    Define CS_DatabaseCheckedText for "Ready! The database was checked but no updates was needed."
    Define CS_DbUpdatedErrorText  for "One or more errors occured while the database was updated. Please check the logfile.\n\nThe program will now close."
    Define CS_UpdateInProgressTxt for ("System locked!\n\nThe database is being updated. Please try again later...\n\n" * "The program will now close.")
#ENDIF

#IFSame Language$Current = Language$Polish
    Define CS_DatabaseNeedsUpdate for ("The database needs to be updated." + "\n\nNB! The database may not be in use while this work is performed. Make sure that nobody else is using the application before clicking 'Yes' below.\n\n" + "Start update now?")
    Define CS_HeaderUpdateText    for "Important!"
    Define CS_DatabaseInUseText   for "There are others using the application/database or at least one table could NOT be opened exclusively. Please close all other applications using the database and try again. The Application will now close."
    Define CS_WorkingHeaderText   for "Working!"
    Define CS_WorkingUpdateText   for "The database is being updated. Please wait..."
    Define CS_DatabaseUpdatedText for "Ready! The database was updated."
    Define CS_DatabaseCheckedText for "Ready! The database was checked but no updates was needed."
    Define CS_DbUpdatedErrorText  for "One or more errors occured while the database was updated. Please check the logfile.\n\nThe program will now close."
    Define CS_UpdateInProgressTxt for ("System locked!\n\nThe database is being updated. Please try again later...\n\n" * "The program will now close.")
#ENDIF

#IFSame Language$Current = Language$Hungarian
    Define CS_DatabaseNeedsUpdate for ("The database needs to be updated." + "\n\nNB! The database may not be in use while this work is performed. Make sure that nobody else is using the application before clicking 'Yes' below.\n\n" + "Start update now?")
    Define CS_HeaderUpdateText    for "Important!"
    Define CS_DatabaseInUseText   for "There are others using the application/database or at least one table could NOT be opened exclusively. Please close all other applications using the database and try again. The Application will now close."
    Define CS_WorkingHeaderText   for "Working!"
    Define CS_WorkingUpdateText   for "The database is being updated. Please wait..."
    Define CS_DatabaseUpdatedText for "Ready! The database was updated."
    Define CS_DatabaseCheckedText for "Ready! The database was checked but no updates was needed."
    Define CS_DbUpdatedErrorText  for "One or more errors occured while the database was updated. Please check the logfile.\n\nThe program will now close."
    Define CS_UpdateInProgressTxt for ("System locked!\n\nThe database is being updated. Please try again later...\n\n" * "The program will now close.")
#ENDIF
