/*

    Open DBDiff 0.9.0.0
    http://opendbiff.codeplex.com/

    Script created by NILS-W540\Nils G. Svedmyr on 2017-10-02 at 11:57:58.

    Created on:  NILS-W540
    Source:      METERMAN on NILS-W540\SQLSTD
    Destination: MeterManCust1 on 192.168.1.42\SQL2012

*/

USE [MeterManCust1]
GO

ALTER TABLE [dbo].[LANG] DROP CONSTRAINT [LANG001_PK]
GO
ALTER TABLE [dbo].[firelink] DROP CONSTRAINT [firelink001_PK]
GO
DROP INDEX [PMTrans002] ON [dbo].[PMTrans]
GO
DROP INDEX [PMWrkDtl005] ON [dbo].[PMWrkDtl]
GO
DROP INDEX [PMTrans003] ON [dbo].[PMTrans]
GO
DROP INDEX [PMWork002] ON [dbo].[PMWork]
GO
DROP INDEX [firelink000] ON [dbo].[firelink]
GO
DROP INDEX [PMPrevYY001] ON [dbo].[PMPrevYY]
GO
DROP INDEX [PMAsset008] ON [dbo].[PMAsset]
GO
DROP INDEX [PMWrkDtl009] ON [dbo].[PMWrkDtl]
GO
DROP INDEX [PMTrans001] ON [dbo].[PMTrans]
GO
DROP INDEX [LANG000] ON [dbo].[LANG]
GO
DROP INDEX [PMWrkAud001] ON [dbo].[PMWrkAud]
GO
DROP INDEX [Doc_Mas002] ON [dbo].[Doc_Mas]
GO
DROP INDEX [Doc_Cat002] ON [dbo].[Doc_Cat]
GO
DROP INDEX [Doc_Mas003] ON [dbo].[Doc_Mas]
GO
DROP INDEX [Doc_Mas004] ON [dbo].[Doc_Mas]
GO
DROP INDEX [PMWork003] ON [dbo].[PMWork]
GO
ALTER TABLE [dbo].[PMWrkAud] ALTER COLUMN [SYS_DateTime] [numeric] (14,0) NOT NULL
GO
ALTER TABLE [dbo].[PMPrevYY] ALTER COLUMN [Open_Date] [datetime] NOT NULL
GO
ALTER TABLE [dbo].[PMPrevYY] DROP COLUMN [Transaction_Dat],[Transaction_Tim],[Remaining_Use_L],[Prior_PER_ERR_D]
GO
ALTER TABLE [dbo].[PMPrevYY] ADD 
[TRANSACTION_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMPrevYY__TRANSA__5F4D1C35] DEFAULT ('1753-01-01'),
[TRANSACTION_TIME] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMPrevYY__TRANSA__6041406E] DEFAULT (''),
[REMAINING_USE_LIFE] [smallint] NOT NULL CONSTRAINT [DF__PMPrevYY__REMAIN__6CA71753] DEFAULT ((0)),
[PRIOR_PER_ERR_DEP] [numeric] (12,2) NOT NULL CONSTRAINT [DF__PMPrevYY__PRIOR___7BE95AE3] DEFAULT ((0))
GO
ALTER TABLE [dbo].[PMWork] DROP COLUMN [Transaction_Dat],[Transaction_Tim]
GO
ALTER TABLE [dbo].[PMWork] ADD 
[TRANSACTION_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMWork__TRANSACT__28BC015A] DEFAULT ('1753-01-01'),
[TRANSACTION_TIME] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMWork__TRANSACT__29B02593] DEFAULT ('')
GO
ALTER TABLE [dbo].[PMWrkAud] DROP COLUMN [PMWrkDtl_Asset_],[PMWrkDtl_Fiscal],[PMWrkDtl_Period]
GO
ALTER TABLE [dbo].[PMWrkAud] ADD 
[PMWRKDTL_ASSET_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__PMWrkAud__PMWRKD__4FC25690] DEFAULT ((0)),
[PMWRKDTL_FISCAL_PERIOD] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMWrkAud__PMWRKD__50B67AC9] DEFAULT (''),
[PMWRKDTL_PERIOD_MM] [smallint] NOT NULL CONSTRAINT [DF__PMWrkAud__PMWRKD__51AA9F02] DEFAULT ((0))
GO
ALTER TABLE [dbo].[PMAsset] DROP COLUMN [Previous_PER_Er],[Previous_PER_E1],[Deptartment_Cod],[Life_Span_Adjus],[TwnStr_Street_F],[TwnStr_Street_T],[Age_Recalculate],[Operational_Com],[Period_Closed_Y],[Fiscal_Period_Y],[Latest_Impairme],[Latest_Addition],[Latest_Residual],[Latest_Insuranc],[Latest_Trans_Ou],[Latest_Trans_In],[Latest_Repl_Cos],[Funding_SubSour],[Funding_SubSou1]
GO
ALTER TABLE [dbo].[PMAsset] ADD 
[PREVIOUS_PER_ERROR] [numeric] (12,2) NOT NULL CONSTRAINT [DF__PMAsset__PREVIOU__55E7A63F] DEFAULT ((0)),
[PREVIOUS_PER_ERR_DEP] [numeric] (12,2) NOT NULL CONSTRAINT [DF__PMAsset__PREVIOU__56DBCA78] DEFAULT ((0)),
[DEPTARTMENT_CODE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMAsset__DEPTART__5AAC5B5C] DEFAULT (''),
[LIFE_SPAN_ADJUSTMENT] [smallint] NOT NULL CONSTRAINT [DF__PMAsset__LIFE_SP__5C94A3CE] DEFAULT ((0)),
[TWNSTR_STREET_FROM] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMAsset__TWNSTR___5F711079] DEFAULT (''),
[TwnStr_Street_To] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMAsset__TwnStr___606534B2] DEFAULT (''),
[AGE_RECALCULATED] [datetime] NOT NULL CONSTRAINT [DF__PMAsset__AGE_REC__6341A15D] DEFAULT ('1753-01-01'),
[Operational_Comments] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMAsset__Operati__6529E9CF] DEFAULT (''),
[PERIOD_CLOSED_YN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMAsset__PERIOD___67123241] DEFAULT (''),
[Fiscal_Period_YYYY] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMAsset__Fiscal___68FA7AB3] DEFAULT (''),
[LATEST_IMPAIRMENT_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMAsset__LATEST___6BD6E75E] DEFAULT ('1753-01-01'),
[LATEST_ADDITION_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMAsset__LATEST___6EB35409] DEFAULT ('1753-01-01'),
[LATEST_RESIDUAL_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMAsset__LATEST___6FA77842] DEFAULT ('1753-01-01'),
[LATEST_INSURANCE_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMAsset__LATEST___709B9C7B] DEFAULT ('1753-01-01'),
[LATEST_TRANS_OUT_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMAsset__LATEST___718FC0B4] DEFAULT ('1753-01-01'),
[LATEST_TRANS_IN_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMAsset__LATEST___7283E4ED] DEFAULT ('1753-01-01'),
[LATEST_REPL_COST_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMAsset__LATEST___73780926] DEFAULT ('1753-01-01'),
[FUNDING_SUBSOURCE] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMAsset__FUNDING__75605198] DEFAULT (''),
[FUNDING_SUBSOURCE2] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMAsset__FUNDING__765475D1] DEFAULT (''),
[Location_5] [char] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMAsset__Locatio__02BA4CB6] DEFAULT ('')
GO
ALTER TABLE [dbo].[PMMast] DROP COLUMN [PMTrans_Type_KE]
GO
ALTER TABLE [dbo].[PMMast] ADD 
[PMTRANS_TYPE_KEY] [numeric] (10,0) NOT NULL CONSTRAINT [DF__PMMast__PMTRANS___37B360D0] DEFAULT ((0))
GO
ALTER TABLE [dbo].[PMHist] DROP COLUMN [TwnStr_Street_F],[TwnStr_Street_T],[PMasset_Fiscal_],[PMAsset_Period_],[CarryingValueDa],[CurrentNetCV_Da],[Acc_Residual_Da],[Transfer_Out_Da],[Transfer_In_Dat],[Insurance_Ref_N],[Replacement_Cos],[Replacement_Co1],[Revaluation_Dat],[Prior_PER_Error],[Prior_ERROR_YE_],[Prior_PER_ERR_D],[Prior_PER_ERR_1],[Original_Life_S],[Life_Span_Adjus],[Life_Span_Adju1],[Remaining_Use_L],[Disposal_Percen],[Acc_Disposal_Co],[YTD_Acc_Disp_Co],[YTD_Acc_Disp_Da],[Disposal_Procee],[Disposal_Scrapp],[Depreciation_Da],[Depreciation_Me],[Deminishing_Per],[Acc_Depreciatio]
GO
ALTER TABLE [dbo].[PMHist] ADD 
[TWNSTR_STREET_FROM] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMHist__TWNSTR_S__10A8795A] DEFAULT (''),
[TWNSTR_STREET_TO] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMHist__TWNSTR_S__119C9D93] DEFAULT (''),
[PMASSET_FISCAL_PERIOD] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMHist__PMASSET___166152B0] DEFAULT (''),
[PMASSET_PERIOD_MM] [smallint] NOT NULL CONSTRAINT [DF__PMHist__PMASSET___175576E9] DEFAULT ((0)),
[CARRYINGVALUEDATE] [datetime] NOT NULL CONSTRAINT [DF__PMHist__CARRYING__288002EB] DEFAULT ('1753-01-01'),
[CURRENTNETCV_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMHist__CURRENTN__2A684B5D] DEFAULT ('1753-01-01'),
[ACC_RESIDUAL_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMHist__ACC_RESI__311548EC] DEFAULT ('1753-01-01'),
[TRANSFER_OUT_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMHist__TRANSFER__32FD915E] DEFAULT ('1753-01-01'),
[TRANSFER_IN_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMHist__TRANSFER__34E5D9D0] DEFAULT ('1753-01-01'),
[INSURANCE_REF_NO] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMHist__INSURANC__35D9FE09] DEFAULT (''),
[REPLACEMENT_COST] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMHist__REPLACEM__38B66AB4] DEFAULT ((0)),
[REPLACEMENT_COST_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMHist__REPLACEM__39AA8EED] DEFAULT ('1753-01-01'),
[REVALUATION_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMHist__REVALUAT__3B92D75F] DEFAULT ('1753-01-01'),
[PRIOR_PER_ERROR_YE] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMHist__PRIOR_PE__3C86FB98] DEFAULT ((0)),
[PRIOR_ERROR_YE_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMHist__PRIOR_ER__3D7B1FD1] DEFAULT ('1753-01-01'),
[PRIOR_PER_ERR_DEPR_YE] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMHist__PRIOR_PE__3E6F440A] DEFAULT ((0)),
[PRIOR_PER_ERR_DEPR_YE_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMHist__PRIOR_PE__3F636843] DEFAULT ('1753-01-01'),
[ORIGINAL_LIFE_SPAN] [smallint] NOT NULL CONSTRAINT [DF__PMHist__ORIGINAL__40578C7C] DEFAULT ((0)),
[LIFE_SPAN_ADJUSTMENT] [smallint] NOT NULL CONSTRAINT [DF__PMHist__LIFE_SPA__414BB0B5] DEFAULT ((0)),
[LIFE_SPAN_ADJUSTED_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMHist__LIFE_SPA__423FD4EE] DEFAULT ('1753-01-01'),
[REMAINING_USE_LIFE] [smallint] NOT NULL CONSTRAINT [DF__PMHist__REMAININ__44281D60] DEFAULT ((0)),
[DISPOSAL_PERCENTAGE] [numeric] (4,2) NOT NULL CONSTRAINT [DF__PMHist__DISPOSAL__461065D2] DEFAULT ((0)),
[ACC_DISPOSAL_COST] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMHist__ACC_DISP__48ECD27D] DEFAULT ((0)),
[YTD_ACC_DISP_COST] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMHist__YTD_ACC___49E0F6B6] DEFAULT ((0)),
[YTD_ACC_DISP_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMHist__YTD_ACC___4AD51AEF] DEFAULT ('1753-01-01'),
[DISPOSAL_PROCEEDS] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMHist__DISPOSAL__4BC93F28] DEFAULT ((0)),
[DISPOSAL_SCRAPPED] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMHist__DISPOSAL__4CBD6361] DEFAULT ((0)),
[DEPRECIATION_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMHist__DEPRECIA__508DF445] DEFAULT ('1753-01-01'),
[DEPRECIATION_METHOD] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMHist__DEPRECIA__5182187E] DEFAULT (''),
[DEMINISHING_PERCENT] [numeric] (4,2) NOT NULL CONSTRAINT [DF__PMHist__DEMINISH__52763CB7] DEFAULT ((0)),
[ACC_DEPRECIATION] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMHist__ACC_DEPR__536A60F0] DEFAULT ((0)),
[Description_5] [char] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMHist__Descript__62ACA480] DEFAULT ('')
GO
ALTER TABLE [dbo].[PMWork] ALTER COLUMN [Period_YYYY] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[PMWork] ALTER COLUMN [Period_MM] [smallint] NOT NULL
GO
ALTER TABLE [dbo].[PMVote] DROP COLUMN [Amount_Differen]
GO
ALTER TABLE [dbo].[PMVote] ADD 
[AMOUNT_DIFFERENCE] [numeric] (10,2) NOT NULL CONSTRAINT [DF__PMVote__AMOUNT_D__0B182688] DEFAULT ((0))
GO
ALTER TABLE [dbo].[PMWrkDtl] ALTER COLUMN [Booked_Out] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[PMWork] ALTER COLUMN [Operator_ManNo] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[PMTrans] ALTER COLUMN [Your_Asset_No] [char] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[PMTrans] DROP COLUMN [PMWrkDtl_PMWork],[PMWrkDtl_Asset_],[PMWrkDtl_Fiscal],[PMWrkDtl_Period],[Transaction_Dat],[Transaction_Tim],[Transaction_Typ],[Life_Span_Adjus],[Impairment_Amou],[Depreciation_Me],[Depreciation_Pe],[Depreciation_Un],[Depreciation_To],[Depreciation_Am],[Disposal_Percen],[DisposalCostAmo],[DisposalProceed],[DisposalScrappi],[Replacement_Cos],[Nominated_Vote_],[Transfer_Sub_Cl],[PriorPER_ErrorD],[CurrentCarrying]
GO
ALTER TABLE [dbo].[PMTrans] ADD 
[PMWRKDTL_PMWORK_ID] [numeric] (10,0) NOT NULL CONSTRAINT [DF__PMTrans__PMWRKDT__302C11AB] DEFAULT ((0)),
[PMWRKDTL_ASSET_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__PMTrans__PMWRKDT__312035E4] DEFAULT ((0)),
[PMWRKDTL_FISCAL_PERIOD] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMTrans__PMWRKDT__32145A1D] DEFAULT (''),
[PMWRKDTL_PERIOD_MM] [smallint] NOT NULL CONSTRAINT [DF__PMTrans__PMWRKDT__33087E56] DEFAULT ((0)),
[TRANSACTION_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMTrans__TRANSAC__33FCA28F] DEFAULT ('1753-01-01'),
[Transaction_Time] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMTrans__Transac__34F0C6C8] DEFAULT (''),
[TRANSACTION_TYPE] [char] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMTrans__TRANSAC__35E4EB01] DEFAULT (''),
[LIFE_SPAN_ADJUSTMENT] [numeric] (6,2) NOT NULL CONSTRAINT [DF__PMTrans__LIFE_SP__3B9DC457] DEFAULT ((0)),
[IMPAIRMENT_AMOUNT] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMTrans__IMPAIRM__3D860CC9] DEFAULT ((0)),
[DEPRECIATION_METHOD] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMTrans__DEPRECI__3E7A3102] DEFAULT (''),
[DEPRECIATION_PERCENTAGE] [numeric] (4,2) NOT NULL CONSTRAINT [DF__PMTrans__DEPRECI__3F6E553B] DEFAULT ((0)),
[DEPRECIATION_UNITS] [numeric] (8,2) NOT NULL CONSTRAINT [DF__PMTrans__DEPRECI__40627974] DEFAULT ((0)),
[DEPRECIATION_TOTAL_UNITS] [numeric] (8,2) NOT NULL CONSTRAINT [DF__PMTrans__DEPRECI__41569DAD] DEFAULT ((0)),
[DEPRECIATION_AMOUNT] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMTrans__DEPRECI__433EE61F] DEFAULT ((0)),
[DISPOSAL_PERCENTAGE] [numeric] (4,2) NOT NULL CONSTRAINT [DF__PMTrans__DISPOSA__45272E91] DEFAULT ((0)),
[DISPOSALCOSTAMOUNT] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMTrans__DISPOSA__470F7703] DEFAULT ((0)),
[DISPOSALPROCEEDS] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMTrans__DISPOSA__48039B3C] DEFAULT ((0)),
[DISPOSALSCRAPPING] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMTrans__DISPOSA__48F7BF75] DEFAULT ((0)),
[REPLACEMENT_COST] [numeric] (12,2) NOT NULL CONSTRAINT [DF__PMTrans__REPLACE__49EBE3AE] DEFAULT ((0)),
[NOMINATED_VOTE_NO] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMTrans__NOMINAT__4BD42C20] DEFAULT (''),
[TRANSFER_SUB_CLASS] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMTrans__TRANSFE__528129AF] DEFAULT (''),
[PRIORPER_ERRORDEPR] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMTrans__PRIORPE__54697221] DEFAULT ((0)),
[CURRENTCARRYINGVALUE] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMTrans__CURRENT__5745DECC] DEFAULT ((0))
GO
ALTER TABLE [dbo].[PMTrans] ALTER COLUMN [Effective_Date] [datetime] NOT NULL
GO
ALTER TABLE [dbo].[PMAsset] ALTER COLUMN [Last_Period_MM] [smallint] NOT NULL
GO
ALTER TABLE [dbo].[sysfile] ADD 
[Plot_CCR] [numeric] (10,0) NOT NULL CONSTRAINT [DF__sysfile__Plot_CC__230BB2F7] DEFAULT ((0)),
[Plot_TmpH] [numeric] (10,0) NOT NULL CONSTRAINT [DF__sysfile__Plot_Tm__23FFD730] DEFAULT ((0)),
[Plot_TmpD] [numeric] (10,0) NOT NULL CONSTRAINT [DF__sysfile__Plot_Tm__24F3FB69] DEFAULT ((0))
GO
ALTER TABLE [dbo].[firelink] DROP COLUMN [RECNUM]
GO
ALTER TABLE [dbo].[firelink] ADD 
[ID] [numeric] (10,0) IDENTITY (1,1) NOT NULL
GO
ALTER TABLE [dbo].[SMITMST] ADD 
[LAT] [numeric] (10,4) NOT NULL CONSTRAINT [DF__SMITMST__LAT__0DDB8BE7] DEFAULT ((0)),
[LONG] [numeric] (10,4) NOT NULL CONSTRAINT [DF__SMITMST__LONG__0ECFB020] DEFAULT ((0))
GO
ALTER TABLE [dbo].[SMS_LOG] ADD 
[TO_WHOM] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__SMS_LOG__TO_WHOM__2C0B0D4C] DEFAULT (''),
[SMS_SENT_YN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__SMS_LOG__SMS_SEN__2CFF3185] DEFAULT ('')
GO
ALTER TABLE [dbo].[EMJCLNK] ADD 
[Combination] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__EMJCLNK__Combina__293F1CFA] DEFAULT ('')
GO
ALTER TABLE [dbo].[CostreqH] ADD 
[PORDER] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__CostreqH__PORDER__4417A107] DEFAULT (''),
[REF] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__CostreqH__REF__450BC540] DEFAULT ('')
GO
ALTER TABLE [dbo].[CompFC] ADD 
[Use_Working_Hrs] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__CompFC__Use_Work__1EC18E87] DEFAULT ('')
GO
ALTER TABLE [dbo].[Doc_Mas] ADD 
[Doc_Mod_ID] [numeric] (6,0) NOT NULL CONSTRAINT [DF__Doc_Mas__Doc_Mod__6E42E4FD] DEFAULT ((0)),
[Doc_eMIS_Module] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Doc_Mas__Doc_eMI__6F370936] DEFAULT (''),
[Control_No] [numeric] (10,0) NOT NULL CONSTRAINT [DF__Doc_Mas__Control__702B2D6F] DEFAULT ((0))
GO
ALTER TABLE [dbo].[Doc_Cat] DROP COLUMN [Doc_Mod_ID],[Docu_Path]
GO
ALTER TABLE [dbo].[PMWrkDtl] ALTER COLUMN [DOC_LINK] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
GO
ALTER TABLE [dbo].[Outage] ALTER COLUMN [Outage_Left] [numeric] (12,2) NOT NULL
GO
ALTER TABLE [dbo].[Pet_CirD] ADD 
[LINE] [int] NOT NULL CONSTRAINT [DF__Pet_CirD__LINE__64EE84ED] DEFAULT ((0)),
[DOC_LINK] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Pet_CirD__DOC_LI__65E2A926] DEFAULT ('')
GO
ALTER TABLE [dbo].[PET_MAST] ADD 
[LINE] [numeric] (10,0) NOT NULL CONSTRAINT [DF__PET_MAST__LINE__6B9B827C] DEFAULT ((0))
GO
ALTER TABLE [dbo].[METCLNK] ADD 
[MeterID] [numeric] (14,0) NOT NULL CONSTRAINT [DF__METCLNK__MeterID__33BCAB6D] DEFAULT ((0))
GO
ALTER TABLE [dbo].[PMWrkDtl] DROP COLUMN [TwnStr_Street_F],[TwnStr_Street_T],[PMasset_Fiscal_],[PMAsset_Period_],[CarryingValueDa],[CurrentNetCV_Da],[Acc_Residual_Da],[Transfer_Out_Da],[Transfer_In_Dat],[Insurance_Ref_N],[Replacement_Cos],[Replacement_Co1],[Revaluation_Dat],[Prior_PER_Error],[Prior_ERROR_YE_],[Prior_PER_ERR_D],[Prior_PER_ERR_1],[Original_Life_S],[Life_Span_Adjus],[Life_Span_Adju1],[Remaining_Use_L],[Disposal_Percen],[Acc_Disposal_Co],[YTD_Acc_Disp_Co],[YTD_Acc_Disp_Da],[Disposal_Procee],[Disposal_Scrapp],[Depreciation_Da],[Depreciation_Me],[Deminishing_Per],[Acc_Depreciatio]
GO
ALTER TABLE [dbo].[PMWrkDtl] ADD 
[TWNSTR_STREET_FROM] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMWrkDtl__TWNSTR__27E96F60] DEFAULT (''),
[TWNSTR_STREET_TO] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMWrkDtl__TWNSTR__28DD9399] DEFAULT (''),
[PMASSET_FISCAL_PERIOD] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMWrkDtl__PMASSE__2DA248B6] DEFAULT (''),
[PMASSET_PERIOD_MM] [smallint] NOT NULL CONSTRAINT [DF__PMWrkDtl__PMASSE__2E966CEF] DEFAULT ((0)),
[CARRYINGVALUEDATE] [datetime] NOT NULL CONSTRAINT [DF__PMWrkDtl__CARRYI__3FC0F8F1] DEFAULT ('1753-01-01'),
[CURRENTNETCV_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMWrkDtl__CURREN__41A94163] DEFAULT ('1753-01-01'),
[ACC_RESIDUAL_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMWrkDtl__ACC_RE__48563EF2] DEFAULT ('1753-01-01'),
[TRANSFER_OUT_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMWrkDtl__TRANSF__4A3E8764] DEFAULT ('1753-01-01'),
[TRANSFER_IN_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMWrkDtl__TRANSF__4C26CFD6] DEFAULT ('1753-01-01'),
[INSURANCE_REF_NO] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMWrkDtl__INSURA__4D1AF40F] DEFAULT (''),
[REPLACEMENT_COST] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMWrkDtl__REPLAC__4FF760BA] DEFAULT ((0)),
[REPLACEMENT_COST_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMWrkDtl__REPLAC__50EB84F3] DEFAULT ('1753-01-01'),
[REVALUATION_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMWrkDtl__REVALU__52D3CD65] DEFAULT ('1753-01-01'),
[PRIOR_PER_ERROR_YE] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMWrkDtl__PRIOR___53C7F19E] DEFAULT ((0)),
[PRIOR_ERROR_YE_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMWrkDtl__PRIOR___54BC15D7] DEFAULT ('1753-01-01'),
[PRIOR_PER_ERR_DEPR_YE] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMWrkDtl__PRIOR___55B03A10] DEFAULT ((0)),
[PRIOR_PER_ERR_DEPR_YE_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMWrkDtl__PRIOR___56A45E49] DEFAULT ('1753-01-01'),
[ORIGINAL_LIFE_SPAN] [smallint] NOT NULL CONSTRAINT [DF__PMWrkDtl__ORIGIN__57988282] DEFAULT ((0)),
[LIFE_SPAN_ADJUSTMENT] [smallint] NOT NULL CONSTRAINT [DF__PMWrkDtl__LIFE_S__588CA6BB] DEFAULT ((0)),
[LIFE_SPAN_ADJUSTED_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMWrkDtl__LIFE_S__5980CAF4] DEFAULT ('1753-01-01'),
[REMAINING_USE_LIFE] [smallint] NOT NULL CONSTRAINT [DF__PMWrkDtl__REMAIN__5B691366] DEFAULT ((0)),
[DISPOSAL_PERCENTAGE] [numeric] (4,2) NOT NULL CONSTRAINT [DF__PMWrkDtl__DISPOS__5D515BD8] DEFAULT ((0)),
[ACC_DISPOSAL_COST] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMWrkDtl__ACC_DI__602DC883] DEFAULT ((0)),
[YTD_ACC_DISP_COST] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMWrkDtl__YTD_AC__6121ECBC] DEFAULT ((0)),
[YTD_ACC_DISP_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMWrkDtl__YTD_AC__621610F5] DEFAULT ('1753-01-01'),
[DISPOSAL_PROCEEDS] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMWrkDtl__DISPOS__630A352E] DEFAULT ((0)),
[DISPOSAL_SCRAPPED] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMWrkDtl__DISPOS__63FE5967] DEFAULT ((0)),
[DEPRECIATION_DATE] [datetime] NOT NULL CONSTRAINT [DF__PMWrkDtl__DEPREC__67CEEA4B] DEFAULT ('1753-01-01'),
[DEPRECIATION_METHOD] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMWrkDtl__DEPREC__68C30E84] DEFAULT (''),
[DEMINISHING_PERCENT] [numeric] (4,2) NOT NULL CONSTRAINT [DF__PMWrkDtl__DEMINI__69B732BD] DEFAULT ((0)),
[ACC_DEPRECIATION] [numeric] (14,2) NOT NULL CONSTRAINT [DF__PMWrkDtl__ACC_DE__6AAB56F6] DEFAULT ((0)),
[Description_5] [char] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PMWrkDtl__Descri__7AE1BEBF] DEFAULT ('')
GO
ALTER TABLE [dbo].[LASTREPORT] ALTER COLUMN [PERCENT] [decimal] (18,2) NOT NULL
GO
CREATE TABLE [dbo].[eMis_Mob]
(
	[Cntrl_num] [int] NOT NULL,
	[Duration] [datetime] NULL,
	[Fault] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Township] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Stand] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street_No] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Comments] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Recieved_HD] [datetime] NULL,
	[Receive_DateT] [datetime] NULL,
	[Start_DateT] [datetime] NULL,
	[Delay_DateT] [datetime] NULL,
	[Completed_DateT] [datetime] NULL,
	[Escalation_Time] [time] NULL,
	[Assigned_unit_Mac] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Completed_Reason] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__eMis_Mobi__Compl__3CBF0154] DEFAULT (''),
	[Delay_Reason] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__eMis_Mobi__Delay__3DB3258D] DEFAULT (''),
	[Revision] [numeric] (10,0) NULL CONSTRAINT [DF__eMis_Mobi__Revis__3EA749C6] DEFAULT ((0)),
	[Data_Changed] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [eMis_Mob001] ON [dbo].[eMis_Mob]
(
	[Cntrl_num] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[FiAllD]
(
	[INCIDENT_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiAllD__INCIDENT__043880D4] DEFAULT ((0)),
	[DATE] [date] NOT NULL CONSTRAINT [DF__FiAllD__DATE__052CA50D] DEFAULT ('0001-01-01'),
	[START_TIME] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiAllD__START_TI__0620C946] DEFAULT (''),
	[END_TIME] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiAllD__END_TIME__0714ED7F] DEFAULT (''),
	[COST_LAB] [numeric] (12,2) NOT NULL CONSTRAINT [DF__FiAllD__COST_LAB__080911B8] DEFAULT ((0)),
	[COST_VEH] [numeric] (12,2) NOT NULL CONSTRAINT [DF__FiAllD__COST_VEH__08FD35F1] DEFAULT ((0)),
	[COST_MAT] [numeric] (12,2) NOT NULL CONSTRAINT [DF__FiAllD__COST_MAT__09F15A2A] DEFAULT ((0)),
	[COST_INV] [numeric] (12,2) NOT NULL CONSTRAINT [DF__FiAllD__COST_INV__0AE57E63] DEFAULT ((0)),
	[COST_TOTAL] [numeric] (12,2) NOT NULL CONSTRAINT [DF__FiAllD__COST_TOT__0BD9A29C] DEFAULT ((0)),
	[Start_DT] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiAllD__Start_DT__0CCDC6D5] DEFAULT (''),
	[End_DT] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiAllD__End_DT__0DC1EB0E] DEFAULT (''),
	[ID] [numeric] (10,0) IDENTITY (1,1) NOT NULL,
	CONSTRAINT [FiAllD002] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [FIALLD001] ON [dbo].[FiAllD]
(
	[INCIDENT_NO] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[eMailLog]
(
	[RECNUM] [int] IDENTITY (1,1) NOT NULL,
	[Control_No] [numeric] (10,0) NOT NULL CONSTRAINT [DF__eMailLog__Contro__7B9CE01B] DEFAULT ((0)),
	[Date] [datetime] NOT NULL CONSTRAINT [DF__eMailLog__Date__7C910454] DEFAULT ('1753-01-01'),
	[Time] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__eMailLog__Time__7D85288D] DEFAULT (''),
	[Source] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__eMailLog__Source__7E794CC6] DEFAULT (''),
	[To_Whom] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__eMailLog__To_Who__7F6D70FF] DEFAULT (''),
	[From_Whom] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__eMailLog__From_W__00619538] DEFAULT (''),
	[Subject] [char] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__eMailLog__Subjec__0155B971] DEFAULT (''),
	[Operator] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__eMailLog__Operat__0249DDAA] DEFAULT (''),
	[Person] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__eMailLog__Person__033E01E3] DEFAULT (''),
	[eMail_Sent_YN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__eMailLog__eMail___0432261C] DEFAULT (''),
	[SysTime] [numeric] (14,0) NOT NULL CONSTRAINT [DF__eMailLog__SysTim__05264A55] DEFAULT ((0))
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [eMailLog000] ON [dbo].[eMailLog]
(
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [eMailLog001] ON [dbo].[eMailLog]
(
	[Control_No] ASC,
	[Date] ASC,
	[Time] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [eMailLog002] ON [dbo].[eMailLog]
(
	[Operator] ASC,
	[Date] ASC,
	[Time] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [eMailLog003] ON [dbo].[eMailLog]
(
	[Person] ASC,
	[Date] ASC,
	[Time] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [eMailLog004] ON [dbo].[eMailLog]
(
	[SysTime] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[FiInvRc]
(
	[INCIDENT_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiInvRc__INCIDEN__0A7B6A0F] DEFAULT ((0)),
	[TS_NO] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiInvRc__TS_NO__0B6F8E48] DEFAULT (''),
	[INVOICE] [numeric] (12,2) NOT NULL CONSTRAINT [DF__FiInvRc__INVOICE__0C63B281] DEFAULT ((0)),
	[DESCRIPTION] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiInvRc__DESCRIP__0D57D6BA] DEFAULT (''),
	[ID] [numeric] (10,0) IDENTITY (1,1) NOT NULL,
	CONSTRAINT [FiInvRc002] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [FIINVRC001] ON [dbo].[FiInvRc]
(
	[INCIDENT_NO] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[eMis_Mo1]
(
	[ID] [int] IDENTITY (1,1) NOT NULL,
	[Cntrl_num] [int] NULL,
	[Duration] [datetime] NULL,
	[Fault] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Township] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Stand] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street_No] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Comments] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Recieved_HD] [datetime] NULL,
	[Receive_DateT] [datetime] NULL,
	[Start_DateT] [datetime] NULL,
	[Delay_DateT] [datetime] NULL,
	[Completed_DateT] [datetime] NULL,
	[Escalation_Time] [time] NULL,
	[Assigned_unit_Mac] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Completed_Reason] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Delay_Reason] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Revision] [numeric] (14,0) NULL,
	[Data_Changed] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Sup_unit_mac] [char] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [eMis_Mo1001] ON [dbo].[eMis_Mo1]
(
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[FiDSect]
(
	[INCEDENT_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiDSect__INCEDEN__694F806E] DEFAULT ((0)),
	[TYPE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiDSect__TYPE__6A43A4A7] DEFAULT (''),
	[NUMBER] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiDSect__NUMBER__6B37C8E0] DEFAULT ((0)),
	[COLOR_CODE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiDSect__COLOR_C__6C2BED19] DEFAULT (''),
	[ID] [numeric] (10,0) IDENTITY (1,1) NOT NULL,
	CONSTRAINT [FiDSect002] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [FIDSECT001] ON [dbo].[FiDSect]
(
	[INCEDENT_NO] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[FiLab]
(
	[MANNO] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiLab__MANNO__730DF4D2] DEFAULT (''),
	[FiALLD_ID] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiLab__FiALLD_ID__7402190B] DEFAULT ((0)),
	[ID] [numeric] (10,0) IDENTITY (1,1) NOT NULL,
	CONSTRAINT [FiLab002] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [FILAB001] ON [dbo].[FiLab]
(
	[FiALLD_ID] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[FiIncidT]
(
	[INCIDENT_NO] [numeric] (10,0) IDENTITY (1,1) NOT NULL,
	[CRDATE] [date] NOT NULL CONSTRAINT [DF__FiIncidT__CRDATE__34078F87] DEFAULT ('0001-01-01'),
	[CRTIME] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__CRTIME__34FBB3C0] DEFAULT (''),
	[CDEPART] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__CDEPAR__35EFD7F9] DEFAULT (''),
	[CARRIVE] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__CARRIV__36E3FC32] DEFAULT (''),
	[CWDATE] [date] NOT NULL CONSTRAINT [DF__FiIncidT__CWDATE__37D8206B] DEFAULT ('0001-01-01'),
	[CWTIME] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__CWTIME__38CC44A4] DEFAULT (''),
	[TDESC] [char] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__TDESC__39C068DD] DEFAULT (''),
	[STREET] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__STREET__3AB48D16] DEFAULT (''),
	[STAND] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__STAND__3BA8B14F] DEFAULT (''),
	[TELEPHONE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__TELEPH__3C9CD588] DEFAULT (''),
	[ACCOUNT] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__ACCOUN__3D90F9C1] DEFAULT (''),
	[COST] [numeric] (16,2) NOT NULL CONSTRAINT [DF__FiIncidT__COST__3E851DFA] DEFAULT ((0)),
	[COMMENTS] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__COMMEN__3F794233] DEFAULT (''),
	[TYPE_INCIDENT] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__TYPE_I__406D666C] DEFAULT (''),
	[ORIGIN] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__ORIGIN__41618AA5] DEFAULT (''),
	[ADDRESS] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__ADDRES__4255AEDE] DEFAULT (''),
	[EXTINGUISHED] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__EXTING__4349D317] DEFAULT (''),
	[OPERATOR] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__OPERAT__443DF750] DEFAULT (''),
	[OPERATOR_DATE] [date] NOT NULL CONSTRAINT [DF__FiIncidT__OPERAT__45321B89] DEFAULT ('0001-01-01'),
	[OPERATOR_TIME] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__OPERAT__46263FC2] DEFAULT (''),
	[OPERATOR_DT] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__OPERAT__471A63FB] DEFAULT (''),
	[CLEAVE_Site] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__CLEAVE__480E8834] DEFAULT (''),
	[RETURN_COMMENTS] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIncidT__RETURN__4902AC6D] DEFAULT (''),
	CONSTRAINT [FIINCIDT001] PRIMARY KEY CLUSTERED
	(
		[INCIDENT_NO] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [FIINCIDT002] ON [dbo].[FiIncidT]
(
	[CRTIME] ASC,
	[INCIDENT_NO] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [FIINCIDT003] ON [dbo].[FiIncidT]
(
	[CRTIME] ASC,
	[CDEPART] ASC,
	[CARRIVE] ASC,
	[CWTIME] ASC,
	[INCIDENT_NO] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[FiIacc]
(
	[INCIDENT_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiIacc__INCIDENT__5A624299] DEFAULT ((0)),
	[ACCOUNT_NO] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIacc__ACCOUNT___5B5666D2] DEFAULT (''),
	[RECHARGE] [numeric] (16,2) NOT NULL CONSTRAINT [DF__FiIacc__RECHARGE__5C4A8B0B] DEFAULT ((0)),
	[TARRIF] [char] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiIacc__TARRIF__5D3EAF44] DEFAULT (''),
	[STANDKEY] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiIacc__STANDKEY__5E32D37D] DEFAULT ((0)),
	[ID] [numeric] (10,0) IDENTITY (1,1) NOT NULL,
	CONSTRAINT [FiIacc003] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [FIIACC001] ON [dbo].[FiIacc]
(
	[INCIDENT_NO] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [FIIACC002] ON [dbo].[FiIacc]
(
	[ACCOUNT_NO] ASC,
	[STANDKEY] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[FiBSect]
(
	[INCENDENT_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiBSect__INCENDE__48E2B0DC] DEFAULT ((0)),
	[TYPE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiBSect__TYPE__49D6D515] DEFAULT (''),
	[QTY] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiBSect__QTY__4ACAF94E] DEFAULT ((0)),
	[ID] [numeric] (10,0) IDENTITY (1,1) NOT NULL,
	CONSTRAINT [FiBSect002] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [FIBSECT001] ON [dbo].[FiBSect]
(
	[INCENDENT_NO] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[FIMAST]
(
	[SHIFT_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FIMAST__SHIFT_NO__26722F87] DEFAULT ((0)),
	[INCIDENT_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FIMAST__INCEDENT__276653C0] DEFAULT ((0))
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[FiCSect]
(
	[INCIDENT_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiCSect__INCIDEN__5DDDCDC2] DEFAULT ((0)),
	[REG_NO] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiCSect__REG_NO__5ED1F1FB] DEFAULT (''),
	[MAKE_AND_TYPE] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiCSect__MAKE_AN__5FC61634] DEFAULT (''),
	[ID] [numeric] (10,0) IDENTITY (1,1) NOT NULL,
	CONSTRAINT [FiCSect002] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [FICSECT001] ON [dbo].[FiCSect]
(
	[INCIDENT_NO] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[FiComm]
(
	[INCIDENT_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiComm__INCIDENT__65D3F545] DEFAULT ((0)),
	[DATETIME] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiComm__DATETIME__66C8197E] DEFAULT (''),
	[COMMENTS] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiComm__COMMENTS__67BC3DB7] DEFAULT (''),
	[ID] [numeric] (10,0) IDENTITY (1,1) NOT NULL,
	[ShortComm] [char] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiComm__ShortCom__68B061F0] DEFAULT (''),
	CONSTRAINT [FiComm002] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [FICOMM001] ON [dbo].[FiComm]
(
	[INCIDENT_NO] ASC,
	[DATETIME] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[SM_PODELH]
(
	[RECNUM] [int] IDENTITY (1,1) NOT NULL,
	[REQ_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__SM_PODELH__REQ_N__4E952F7A] DEFAULT ((0)),
	[REQ_LINE] [numeric] (10,0) NOT NULL CONSTRAINT [DF__SM_PODELH__REQ_L__4F8953B3] DEFAULT ((0)),
	[DATE] [datetime] NOT NULL CONSTRAINT [DF__SM_PODELH__DATE__507D77EC] DEFAULT (''),
	[QTY] [numeric] (10,0) NOT NULL CONSTRAINT [DF__SM_PODELH__QTY__51719C25] DEFAULT ((0)),
	[COMPLETED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__SM_PODELH__COMPL__5265C05E] DEFAULT (''),
	[LINE_NO] [int] NOT NULL CONSTRAINT [DF__SM_PODELH__LINE___5359E497] DEFAULT ((0))
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [SM_PODELH000] ON [dbo].[SM_PODELH]
(
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [SM_PODELH001] ON [dbo].[SM_PODELH]
(
	[REQ_NO] ASC,
	[LINE_NO] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[SQL_DASH]
(
	[CTRL] [numeric] (10,0) NOT NULL CONSTRAINT [DF__SQL_DASH__CTRL__0FEC5ADD] DEFAULT ((0)),
	[CRDATE] [datetime] NULL CONSTRAINT [DF__SQL_DASH__CRDATE__10E07F16] DEFAULT (''),
	[CRTIME] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__SQL_DASH__CRTIME__11D4A34F] DEFAULT (''),
	[CWDATE] [datetime] NULL,
	[CWTIME] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__SQL_DASH__CWTIME__13BCEBC1] DEFAULT (''),
	[STATUS] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__SQL_DASH__STATUS__14B10FFA] DEFAULT (''),
	[STATUS_DATE] [datetime] NULL CONSTRAINT [DF__SQL_DASH__STATUS__15A53433] DEFAULT (''),
	[DEPT] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__SQL_DASH__DEPT__1699586C] DEFAULT (''),
	[FAULT_TYPE] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__SQL_DASH__FAULT___178D7CA5] DEFAULT (''),
	[AREA] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__SQL_DASH__AREA__1881A0DE] DEFAULT (''),
	[GISKEY] [char] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__SQL_DASH__GISKEY__1975C517] DEFAULT (''),
	[TOWNSHIP] [char] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__SQL_DASH__TOWNSH__1A69E950] DEFAULT (''),
	[RESPONSE_TIME] [numeric] (12,2) NULL CONSTRAINT [DF__SQL_DASH__RESPON__1B5E0D89] DEFAULT (''),
	[STREET] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STREET_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [SQL_DASH001] ON [dbo].[SQL_DASH]
(
	[CTRL] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[SEWBULK]
(
	[RECNUM] [int] IDENTITY (1,1) NOT NULL,
	[CONTROL] [numeric] (10,0) NOT NULL CONSTRAINT [DF__SEWBULK__CONTROL__6C458DF2] DEFAULT ((0)),
	[TIMESHEET] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__SEWBULK__TIMESHE__6D39B22B] DEFAULT (''),
	[LOADS] [smallint] NOT NULL CONSTRAINT [DF__SEWBULK__LOADS__6E2DD664] DEFAULT ((0)),
	[TRIPS] [smallint] NOT NULL CONSTRAINT [DF__SEWBULK__TRIPS__6F21FA9D] DEFAULT ((0))
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [SEWBULK000] ON [dbo].[SEWBULK]
(
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [SEWBULK001] ON [dbo].[SEWBULK]
(
	[CONTROL] ASC,
	[TIMESHEET] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[PlotTmpH]
(
	[RECNUM] [int] IDENTITY (1,1) NOT NULL,
	[RefID] [numeric] (10,0) NOT NULL CONSTRAINT [DF__PlotTmpH__RefID__3159D24E] DEFAULT ((0)),
	[Type] [char] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PlotTmpH__Type__324DF687] DEFAULT (''),
	[Description] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PlotTmpH__Descri__33421AC0] DEFAULT (''),
	[Branch_Lines] [smallint] NOT NULL CONSTRAINT [DF__PlotTmpH__Branch__34363EF9] DEFAULT ((0)),
	CONSTRAINT [PlotTmpH001_PK] PRIMARY KEY CLUSTERED
	(
		[RefID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PlotTmpH000] ON [dbo].[PlotTmpH]
(
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [PlotTmpH002] ON [dbo].[PlotTmpH]
(
	[Type] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[PO_DELD]
(
	[RECNUM] [int] IDENTITY (1,1) NOT NULL,
	[REQ_No] [numeric] (10,0) NOT NULL CONSTRAINT [DF__PO_DELD__REQ_No__4A3A8EB1] DEFAULT ((0)),
	[REQ_LINE] [numeric] (10,0) NOT NULL CONSTRAINT [DF__PO_DELD__REQ_LIN__4B2EB2EA] DEFAULT ((0)),
	[DATE] [datetime] NOT NULL CONSTRAINT [DF__PO_DELD__DATE__4C22D723] DEFAULT (''),
	[METER NO] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PO_DELD__METER N__4D16FB5C] DEFAULT ('')
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PO_DELD000] ON [dbo].[PO_DELD]
(
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [PO_DELD001] ON [dbo].[PO_DELD]
(
	[REQ_LINE] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[STRM]
(
	[RECNUM] [int] IDENTITY (1,1) NOT NULL,
	[STRM_ID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__STRM_ID__1C5A2328] DEFAULT (''),
	[STRM_NO] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__STRM_NO__1D4E4761] DEFAULT (''),
	[STREET_NAME] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__STREET_NAM__1E426B9A] DEFAULT (''),
	[STREET_SEC] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__STREET_SEC__1F368FD3] DEFAULT (''),
	[STREET_FROM] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__STREET_FRO__202AB40C] DEFAULT (''),
	[STREET_TO] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__STREET_TO__211ED845] DEFAULT (''),
	[TOWNSHIP] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__TOWNSHIP__2212FC7E] DEFAULT (''),
	[LENGTH] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__LENGTH__230720B7] DEFAULT (''),
	[WIDTH] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__WIDTH__23FB44F0] DEFAULT (''),
	[DIAMETER] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__DIAMETER__24EF6929] DEFAULT (''),
	[CLASS] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__CLASS__25E38D62] DEFAULT (''),
	[PCI] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__PCI__26D7B19B] DEFAULT (''),
	[CONDITION_CAT] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__CONDITION___27CBD5D4] DEFAULT (''),
	[REPAIR_TYPE] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__REPAIR_TYP__28BFFA0D] DEFAULT (''),
	[ESTMATE_COST] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__ESTMATE_CO__29B41E46] DEFAULT (''),
	[YEAR] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__YEAR__2AA8427F] DEFAULT (''),
	[TRENCH] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__TRENCH__2B9C66B8] DEFAULT (''),
	[TRENCH_SCH_DATE] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__TRENCH_SCH__2C908AF1] DEFAULT (''),
	[TRENCH_LENGTH] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__TRENCH_LEN__2D84AF2A] DEFAULT (''),
	[TRENCH_WIDTH] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__TRENCH_WID__2E78D363] DEFAULT (''),
	[NO_ACTIVITY] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__NO_ACTIVIT__2F6CF79C] DEFAULT (''),
	[TYPE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRM__TYPE__30611BD5] DEFAULT ('')
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [STRM000] ON [dbo].[STRM]
(
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [STRM001] ON [dbo].[STRM]
(
	[STRM_ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [STRM002] ON [dbo].[STRM]
(
	[STREET_NAME] ASC,
	[STREET_SEC] ASC,
	[STREET_FROM] ASC,
	[STREET_TO] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [STRM003] ON [dbo].[STRM]
(
	[STRM_NO] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [STRM004] ON [dbo].[STRM]
(
	[TOWNSHIP] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[TPSTAN]
(
	[RECNUM] [int] IDENTITY (1,1) NOT NULL,
	[APP_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__TPSTAN__APP_NO__69692147] DEFAULT ((0)),
	[STANDKEY] [numeric] (10,0) NOT NULL CONSTRAINT [DF__TPSTAN__STANDKEY__6A5D4580] DEFAULT ((0))
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [TPSTAN000] ON [dbo].[TPSTAN]
(
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [TPSTAN001] ON [dbo].[TPSTAN]
(
	[APP_NO] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [TPSTAN002] ON [dbo].[TPSTAN]
(
	[STANDKEY] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[WS_Cases]
(
	[ID] [int] IDENTITY (1,1) NOT NULL,
	[CaseNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CaseStatus] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Technician] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Feedback] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FeedbackChannel] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[MobileNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Created] [datetime] NOT NULL CONSTRAINT [DF_WS_Cases_Created] DEFAULT (getdate()),
	[StatusSent] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SentMessage] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StatusMessage] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT [PK_WS_Cases] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Tabi_Data]
(
	[Agent_ID] [int] NULL,
	[Ani] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Call_Date] [datetime] NULL,
	[Call_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Campaign] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Comment] [varchar] (900) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Customer_ID] [int] NULL,
	[dnis] [int] NULL,
	[Duration] [int] NULL,
	[End_Reason] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Memo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Queue] [int] NULL,
	[Status_Code] [int] NULL,
	[Status_Detail] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Status_Group] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Status_Text] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Firstname] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Lastname] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Row_ID] [int] IDENTITY (1,1) NOT NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[STRMACT]
(
	[RECNUM] [int] IDENTITY (1,1) NOT NULL,
	[STRM_ID] [numeric] (10,0) NOT NULL CONSTRAINT [DF__STRMACT__STRM_ID__5FDFB70D] DEFAULT ((0)),
	[CTRL] [numeric] (10,0) NOT NULL CONSTRAINT [DF__STRMACT__CTRL__60D3DB46] DEFAULT ((0)),
	[DATE] [date] NOT NULL CONSTRAINT [DF__STRMACT__DATE__61C7FF7F] DEFAULT ('0001-01-01'),
	[ACTIVITY] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRMACT__ACTIVIT__62BC23B8] DEFAULT (''),
	[COST] [numeric] (12,2) NOT NULL CONSTRAINT [DF__STRMACT__COST__63B047F1] DEFAULT ((0))
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [STRMACT000] ON [dbo].[STRMACT]
(
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [STRMACT001] ON [dbo].[STRMACT]
(
	[STRM_ID] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [STRMACT002] ON [dbo].[STRMACT]
(
	[CTRL] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[STRMDESC]
(
	[RECNUM] [int] IDENTITY (1,1) NOT NULL,
	[ACTIVITY] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRMDESC__ACTIVI__65989063] DEFAULT (''),
	[WORK_TYPE] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRMDESC__WORK_T__668CB49C] DEFAULT (''),
	[UNIT] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__STRMDESC__UNIT__6780D8D5] DEFAULT ('')
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [STRMDESC000] ON [dbo].[STRMDESC]
(
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [STRMDESC001] ON [dbo].[STRMDESC]
(
	[ACTIVITY] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[FiVeh]
(
	[SHIFT_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiVeh__SHIFT_NO__26238484] DEFAULT ((0)),
	[VEHICLE] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiVeh__VEHICLE__2717A8BD] DEFAULT (''),
	[ID] [numeric] (10,0) IDENTITY (1,1) NOT NULL,
	CONSTRAINT [FiVeh001_PK] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [FIVEH001] ON [dbo].[FiVeh]
(
	[SHIFT_NO] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[FIVEHRC]
(
	[VEHNO] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FIVEHRC__VEHNO__4C142342] DEFAULT (''),
	[SHRS] [smallint] NOT NULL CONSTRAINT [DF__FIVEHRC__SHRS__4D08477B] DEFAULT ((0)),
	[EHRS] [smallint] NOT NULL CONSTRAINT [DF__FIVEHRC__EHRS__4DFC6BB4] DEFAULT ((0)),
	[SKM] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FIVEHRC__SKM__4EF08FED] DEFAULT ((0)),
	[EKM] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FIVEHRC__EKM__4FE4B426] DEFAULT ((0)),
	[DATE] [date] NOT NULL CONSTRAINT [DF__FIVEHRC__DATE__50D8D85F] DEFAULT ('0001-01-01'),
	[FiALLD_ID] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FIVEHRC__FiALLD___51CCFC98] DEFAULT ((0)),
	[ID] [numeric] (10,0) IDENTITY (1,1) NOT NULL,
	CONSTRAINT [FIVEHRC002] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [FIVEHRC001] ON [dbo].[FIVEHRC]
(
	[FiALLD_ID] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[FiShift]
(
	[SHIFT_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiShift__SHIFT_N__6826520B] DEFAULT ((0)),
	[SHIFT_NAME] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiShift__SHIFT_N__691A7644] DEFAULT (''),
	[TIME_START] [date] NOT NULL CONSTRAINT [DF__FiShift__TIME_ST__6A0E9A7D] DEFAULT ('0001-01-01'),
	[TIMES] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiShift__TIMES__6B02BEB6] DEFAULT (''),
	[TIME_END] [date] NOT NULL CONSTRAINT [DF__FiShift__TIME_EN__6BF6E2EF] DEFAULT ('0001-01-01'),
	[TIMEE] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiShift__TIMEE__6CEB0728] DEFAULT (''),
	[AREA] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiShift__AREA__6DDF2B61] DEFAULT (''),
	[STATUS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiShift__STATUS__6ED34F9A] DEFAULT (''),
	[OPERATOR] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiShift__OPERATO__6FC773D3] DEFAULT (''),
	[OPERATOR_DATE] [date] NOT NULL CONSTRAINT [DF__FiShift__OPERATO__70BB980C] DEFAULT ('0001-01-01'),
	[OPERATOR_TIME] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiShift__OPERATO__71AFBC45] DEFAULT (''),
	[OPERATOR_DT] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiShift__OPERATO__72A3E07E] DEFAULT (''),
	[OPCLOSE] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiShift__OPCLOSE__739804B7] DEFAULT (''),
	[OPCLOSE_DATE] [date] NOT NULL CONSTRAINT [DF__FiShift__OPCLOSE__748C28F0] DEFAULT ('0001-01-01'),
	[OPCLOSE_TIME] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiShift__OPCLOSE__75804D29] DEFAULT (''),
	[OPCLOSE_DT] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiShift__OPCLOSE__76747162] DEFAULT (''),
	[Shift_Start_DT] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiShift__Shift_S__7768959B] DEFAULT (''),
	[Shift_End_DT] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiShift__Shift_E__785CB9D4] DEFAULT (''),
	[ID] [numeric] (10,0) IDENTITY (1,1) NOT NULL,
	CONSTRAINT [FiShift004] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [FISHIFT001] ON [dbo].[FiShift]
(
	[SHIFT_NO] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [FISHIFT002] ON [dbo].[FiShift]
(
	[SHIFT_NAME] ASC,
	[STATUS] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [FISHIFT003] ON [dbo].[FiShift]
(
	[TIME_START] ASC,
	[TIME_END] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[FiMatRc]
(
	[COMMODITY] [char] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiMatRc__COMMODI__69848A98] DEFAULT (''),
	[QTY] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiMatRc__QTY__6A78AED1] DEFAULT ((0)),
	[PRICE] [numeric] (12,2) NOT NULL CONSTRAINT [DF__FiMatRc__PRICE__6B6CD30A] DEFAULT ((0)),
	[FiALLD_ID] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiMatRc__FiALLD___6C60F743] DEFAULT ((0)),
	[ID] [numeric] (10,0) IDENTITY (1,1) NOT NULL,
	CONSTRAINT [FiMatRc002] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [FIMATRC001] ON [dbo].[FiMatRc]
(
	[FiALLD_ID] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[FiPers]
(
	[SHIFT_NO] [numeric] (10,0) NOT NULL CONSTRAINT [DF__FiPers__SHIFT_NO__401860B1] DEFAULT ((0)),
	[MANNO] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiPers__MANNO__410C84EA] DEFAULT (''),
	[TIME_START] [date] NOT NULL CONSTRAINT [DF__FiPers__TIME_STA__4200A923] DEFAULT ('0001-01-01'),
	[TIME_END] [date] NOT NULL CONSTRAINT [DF__FiPers__TIME_END__42F4CD5C] DEFAULT ('0001-01-01'),
	[SHORT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiPers__SHORT__43E8F195] DEFAULT (''),
	[TIMES] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiPers__TIMES__44DD15CE] DEFAULT (''),
	[TIMEE] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiPers__TIMEE__45D13A07] DEFAULT (''),
	[StartTime_DT] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiPers__StartTim__46C55E40] DEFAULT (''),
	[EndTime_DT] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__FiPers__EndTime___47B98279] DEFAULT (''),
	[ID] [numeric] (10,0) IDENTITY (1,1) NOT NULL,
	CONSTRAINT [FiPers002] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [FIPERS001] ON [dbo].[FiPers]
(
	[SHIFT_NO] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[MapConfig]
(
	[Longitude] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__MapConfig__Longi__0A5B6E7E] DEFAULT (''),
	[Latitude] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__MapConfig__Latit__0B4F92B7] DEFAULT (''),
	[ZoomFactor] [int] NOT NULL CONSTRAINT [DF__MapConfig__ZoomF__0C43B6F0] DEFAULT ((0)),
	[MapGroupID] [bigint] NOT NULL,
	[MapLayerID] [bigint] NOT NULL,
	[MapServerAddress] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[MapName] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[MapWebAddress] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__MapConfig__MapWe__0D37DB29] DEFAULT ('')
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Plot_CCR]
(
	[RECNUM] [int] IDENTITY (1,1) NOT NULL,
	[RefID] [numeric] (10,0) NOT NULL CONSTRAINT [DF__Plot_CCR__RefID__26DC43DB] DEFAULT ((0)),
	[Ctrl] [numeric] (10,0) NOT NULL CONSTRAINT [DF__Plot_CCR__Ctrl__27D06814] DEFAULT ((0)),
	[Start_Date] [datetime] NOT NULL CONSTRAINT [DF__Plot_CCR__Start___28C48C4D] DEFAULT ('1753-01-01'),
	[End_Date] [datetime] NOT NULL CONSTRAINT [DF__Plot_CCR__End_Da__29B8B086] DEFAULT ('1753-01-01'),
	[Status] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Plot_CCR__Status__2AACD4BF] DEFAULT (''),
	[Days] [smallint] NOT NULL CONSTRAINT [DF__Plot_CCR__Days__2BA0F8F8] DEFAULT ((0)),
	[Complete_YN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Plot_CCR__Comple__2C951D31] DEFAULT (''),
	[Note] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Plot_CCR__Note__2D89416A] DEFAULT (''),
	CONSTRAINT [Plot_CCR001_PK] PRIMARY KEY CLUSTERED
	(
		[RefID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Plot_CCR000] ON [dbo].[Plot_CCR]
(
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [Plot_CCR002] ON [dbo].[Plot_CCR]
(
	[Start_Date] ASC,
	[Status] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[PlotTmpD]
(
	[RECNUM] [int] IDENTITY (1,1) NOT NULL,
	[RefID] [numeric] (10,0) NOT NULL CONSTRAINT [DF__PlotTmpD__RefID__3806CFDD] DEFAULT ((0)),
	[PlotTmpH_RefID] [numeric] (10,0) NOT NULL CONSTRAINT [DF__PlotTmpD__PlotTm__38FAF416] DEFAULT ((0)),
	[Type] [char] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PlotTmpD__Type__39EF184F] DEFAULT (''),
	[Line] [smallint] NOT NULL CONSTRAINT [DF__PlotTmpD__Line__3AE33C88] DEFAULT ((0)),
	[Code] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PlotTmpD__Code__3BD760C1] DEFAULT (''),
	[Description] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PlotTmpD__Descri__3CCB84FA] DEFAULT (''),
	[Value] [smallint] NOT NULL CONSTRAINT [DF__PlotTmpD__Value__3DBFA933] DEFAULT ((0)),
	[Comments] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__PlotTmpD__Commen__3EB3CD6C] DEFAULT (''),
	CONSTRAINT [PlotTmpD001_PK] PRIMARY KEY CLUSTERED
	(
		[RefID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PlotTmpD000] ON [dbo].[PlotTmpD]
(
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [PlotTmpD002] ON [dbo].[PlotTmpD]
(
	[Type] ASC,
	[Line] ASC,
	[Code] ASC,
	[RefID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[OPR_DEPT]
(
	[RECNUM] [int] IDENTITY (1,1) NOT NULL,
	[ManNo] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__OPR_DEPT__ManNo__6589112B] DEFAULT (''),
	[Meter_Dept] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__OPR_DEPT__Meter___667D3564] DEFAULT (''),
	[PowerMeter] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__OPR_DEPT__PowerM__6771599D] DEFAULT ('')
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [OPR_DEPT000] ON [dbo].[OPR_DEPT]
(
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [OPR_DEPT001] ON [dbo].[OPR_DEPT]
(
	[ManNo] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [OPR_DEPT002] ON [dbo].[OPR_DEPT]
(
	[ManNo] ASC,
	[Meter_Dept] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[MapGroup]
(
	[ID] [int] IDENTITY (1,1) NOT NULL,
	[Group] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__MapGroup__Group__2B6BEECE] DEFAULT (''),
	CONSTRAINT [MapGroup001_PK] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [MapGroup002] ON [dbo].[MapGroup]
(
	[ID] ASC,
	[Group] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[MapLayer]
(
	[ID] [int] IDENTITY (1,1) NOT NULL,
	[GroupID] [int] NOT NULL CONSTRAINT [DF__MapLayer__GroupI__213ED3D6] DEFAULT ((0)),
	[DisplayLayer] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__MapLayer__Displa__2232F80F] DEFAULT (''),
	[RealLayer] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__MapLayer__RealLa__23271C48] DEFAULT (''),
	[Visible] [tinyint] NOT NULL CONSTRAINT [DF__MapLayer__Visibl__241B4081] DEFAULT ((0)),
	[Active] [tinyint] NOT NULL CONSTRAINT [DF__MapLayer__Active__250F64BA] DEFAULT ((0)),
	[QueryFieldName] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__MapLayer__QueryF__260388F3] DEFAULT (''),
	[ZoomFactor] [int] NOT NULL CONSTRAINT [DF__MapLayer__ZoomFa__26F7AD2C] DEFAULT ((0)),
	CONSTRAINT [MapLayer001_PK] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [MapLayer002] ON [dbo].[MapLayer]
(
	[GroupID] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [MapLayer003] ON [dbo].[MapLayer]
(
	[DisplayLayer] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [MapLayer004] ON [dbo].[MapLayer]
(
	[RealLayer] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [MapLayer005] ON [dbo].[MapLayer]
(
	[Visible] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [MapLayer006] ON [dbo].[MapLayer]
(
	[Active] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [MapLayer007] ON [dbo].[MapLayer]
(
	[QueryFieldName] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[BPLANM]
(
	[RECNUM] [int] IDENTITY (1,1) NOT NULL,
	[PLAN_NO] [numeric] (14,0) NOT NULL CONSTRAINT [DF__BPLANM__PLAN_NO__6192F555] DEFAULT ((0)),
	[DATE] [date] NOT NULL CONSTRAINT [DF__BPLANM__DATE__6287198E] DEFAULT ('0001-01-01'),
	[DEPT] [char] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__BPLANM__DEPT__637B3DC7] DEFAULT (''),
	[DEPOT] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__BPLANM__DEPOT__646F6200] DEFAULT (''),
	[COMMENTS] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__BPLANM__COMMENTS__65638639] DEFAULT ('')
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [BPLANM000] ON [dbo].[BPLANM]
(
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [BPLANM001] ON [dbo].[BPLANM]
(
	[PLAN_NO] ASC,
	[DATE] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [BPLANM002] ON [dbo].[BPLANM]
(
	[DATE] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE [dbo].[DbVersion]
(
	[DatabaseVersion] [numeric] (6,2) NOT NULL CONSTRAINT [DF__DBVERSION__Datab__6B41EA81] DEFAULT ((0))
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Calls]
(
	[ID] [int] IDENTITY (1,1) NOT NULL,
	[Case_Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Department] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Division] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Category] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SubCategory] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Description] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Street3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Province] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Case_Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CallTypes] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SLA] [int] NULL,
	[DateTimeStampSent] [datetime] NULL,
	[Processed] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT [PK_eMIS_Eku_CRM_Rec] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Calls_v2]
(
	[ID] [int] IDENTITY (1,1) NOT NULL,
	[CTRL] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Department] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Division] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Category] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Description] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[StreetName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[StreetNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FAULT_TYPE] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[RESPONSE_TIME] [int] NOT NULL,
	[CRDATETIME] [datetime] NOT NULL,
	[TelephoneNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Area] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Township] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Processed] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__Calls_v2__Proces__15502E78] DEFAULT (''),
	CONSTRAINT [PK_eMIS_Eku_CRM_Rec_v2] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DOC_SYS]
(
	[DocuMAN_Path] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__DOC_SYS__DocuMAN__6D83CAEE] DEFAULT (''),
	[Doc_Mod_ID] [numeric] (10,0) NOT NULL CONSTRAINT [DF__DOC_SYS__Doc_Mod__6E77EF27] DEFAULT ((0)),
	[Doc_Cat_ID] [numeric] (10,0) NOT NULL CONSTRAINT [DF__DOC_SYS__Doc_Cat__6F6C1360] DEFAULT ((0)),
	[Doc_Mas_ID] [numeric] (10,0) NOT NULL CONSTRAINT [DF__DOC_SYS__Doc_Mas__70603799] DEFAULT ((0))
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TempLANG]
(
	[RECNUM] [int] IDENTITY (1,1) NOT NULL,
	[en] [char] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__LANG__en__353F71CB] DEFAULT (''),
	[TRANSLATION] [char] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__LANG__TRANSLATIO__1C7DE5A2] DEFAULT (''),
	[LANGUAGE] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__LANG__LANGUAGE__1A959D30] DEFAULT ('')

) ON [PRIMARY]
GO

SET IDENTITY_INSERT [dbo].[TempLANG] ON
INSERT INTO [dbo].[TempLANG] ([RECNUM],[en],[TRANSLATION],[LANGUAGE]) SELECT [RECNUM],(''),[TRANSLATION],[LANGUAGE] FROM [dbo].[LANG]
SET IDENTITY_INSERT [dbo].[TempLANG] OFF
GO

DROP TABLE [dbo].[LANG]
GO
EXEC sp_rename N'[dbo].[TempLANG]',N'LANG', 'OBJECT'
GO


CREATE UNIQUE NONCLUSTERED INDEX [PMWork003] ON [dbo].[PMWork]
(
	[Operator_ManNo] ASC,
	[Period_YYYY] ASC,
	[Period_MM] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMWrkAud001] ON [dbo].[PMWrkAud]
(
	[PMWRKDTL_ASSET_NO] ASC,
	[PMWRKDTL_FISCAL_PERIOD] ASC,
	[PMWRKDTL_PERIOD_MM] ASC,
	[SYS_DateTime] DESC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Doc_Mas006] ON [dbo].[Doc_Mas]
(
	[Doc_Cat_ID] ASC,
	[Category] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMWrkDtl009] ON [dbo].[PMWrkDtl]
(
	[DOC_LINK] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMWrkDtl005] ON [dbo].[PMWrkDtl]
(
	[Booked_Out] ASC,
	[Fiscal_Period] ASC,
	[Period_MM] ASC,
	[Asset_SubClass] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [firelink001_PK] ON [dbo].[firelink]
(
	[STAND_KEY] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [LANG000] ON [dbo].[LANG]
(
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMPrevYY001] ON [dbo].[PMPrevYY]
(
	[Asset_No] ASC,
	[Open_Date] DESC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMAsset008] ON [dbo].[PMAsset]
(
	[Fiscal_Period_YYYY] ASC,
	[Last_Period_MM] ASC,
	[ASSET_NO] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMTrans002] ON [dbo].[PMTrans]
(
	[Your_Asset_No] ASC,
	[TRANSACTION_DATE] DESC,
	[Transaction_Time] DESC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMWork002] ON [dbo].[PMWork]
(
	[Work_Book_No] ASC,
	[Period_YYYY] DESC,
	[Period_MM] DESC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Pet_CirD003] ON [dbo].[Pet_CirD]
(
	[LINE] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMTrans003] ON [dbo].[PMTrans]
(
	[PMWRKDTL_ASSET_NO] ASC,
	[PMWRKDTL_FISCAL_PERIOD] ASC,
	[PMWRKDTL_PERIOD_MM] ASC,
	[Effective_Date] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [SCHLIST007] ON [dbo].[SCHLIST]
(
	[TYPE_OF_ITEM] ASC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Doc_Mas004] ON [dbo].[Doc_Mas]
(
	[Link_ID] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [CODEMAST000] ON [dbo].[CODEMAST]
(
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Doc_Mas003] ON [dbo].[Doc_Mas]
(
	[Doc_ID] ASC,
	[File_Ext] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Doc_Cat002] ON [dbo].[Doc_Cat]
(
	[Category] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Doc_Mas005] ON [dbo].[Doc_Mas]
(
	[Doc_eMIS_Module] ASC,
	[Category] ASC,
	[Control_No] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [Doc_Mas002] ON [dbo].[Doc_Mas]
(
	[Docu_Path] ASC,
	[ID] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [PMTrans001] ON [dbo].[PMTrans]
(
	[PMWRKDTL_ASSET_NO] ASC,
	[PMWRKDTL_FISCAL_PERIOD] ASC,
	[PMWRKDTL_PERIOD_MM] ASC,
	[TRANSACTION_DATE] DESC,
	[Transaction_Time] DESC,
	[RECNUM] ASC
) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LANG] ADD CONSTRAINT [LANG001_PK] PRIMARY KEY CLUSTERED
	(
		[en] ASC,
		[LANGUAGE] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[firelink] ADD CONSTRAINT [firelink002] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
